// Copyright (c) 2026 Orime, Inc.
// SPDX-License-Identifier: LicenseRef-BSAL-1.0

/**
 * Payment repository — data access for the payments table.
 */

import { eq, and, desc, inArray, isNull, sql } from "drizzle-orm";
import { db } from "@breatic/core";
import type { DbTx } from "@breatic/core";
import { payments, users, creditLots, purchaseConsents } from "@breatic/core";
import type { PaymentEntity } from "@breatic/shared";

/**
 * Map a raw `payments` table row to a `PaymentEntity` domain object,
 * defaulting a null `metadata` JSONB column to an empty object.
 * @param row - Raw row selected from the `payments` table
 * @returns The mapped payment entity
 */
function toEntity(row: typeof payments.$inferSelect): PaymentEntity {
  return {
    id: row.id,
    userId: row.userId,
    stripeSessionId: row.stripeSessionId,
    stripePaymentIntentId: row.stripePaymentIntentId,
    amountCents: row.amountCents,
    currency: row.currency,
    status: row.status,
    creditsGranted: row.creditsGranted,
    metadata: (row.metadata ?? {}),
    createdAt: row.createdAt,
    updatedAt: row.updatedAt,
  };
}

/**
 * Create a new payment record (status defaults to "pending" at the DB level).
 * @param data - Payment fields to insert
 * @param data.id - The row's id, generated by the caller before the Stripe
 *   session so the Back-button URL can carry it. Left out, the database picks one.
 * @param data.userId - User who initiated the purchase
 * @param data.stripeSessionId - Stripe Checkout session ID for this payment
 * @param data.amountCents - Charge amount in the smallest currency unit (cents)
 * @param data.creditsGranted - Number of credits granted once the payment completes
 * @param data.currency - ISO currency code (defaults to "usd")
 * @param data.metadata - Arbitrary JSONB metadata (defaults to an empty object)
 * @returns The inserted payment entity
 */
export async function createPayment(data: {
  id?: string;
  userId: string;
  stripeSessionId: string;
  amountCents: number;
  creditsGranted: number;
  currency?: string;
  metadata?: Record<string, unknown>;
}): Promise<PaymentEntity> {
  const rows = await db
    .insert(payments)
    .values({
      ...(data.id === undefined ? {} : { id: data.id }),
      userId: data.userId,
      stripeSessionId: data.stripeSessionId,
      amountCents: data.amountCents,
      creditsGranted: data.creditsGranted,
      currency: data.currency ?? "usd",
      metadata: data.metadata ?? {},
    })
    .returning();
  return toEntity(rows[0]!);
}

/**
 * Get a payment by ID.
 * @param id - Payment UUID
 * @returns The payment entity, or null if not found
 */
export async function getPaymentById(id: string): Promise<PaymentEntity | null> {
  const rows = await db.select().from(payments).where(eq(payments.id, id)).limit(1);
  return rows[0] ? toEntity(rows[0]) : null;
}

/**
 * Get a payment by Stripe session ID.
 * @param sessionId - Stripe Checkout session ID
 * @returns The payment entity, or null if no payment matches the session
 */
export async function getPaymentByStripeSessionId(sessionId: string): Promise<PaymentEntity | null> {
  const rows = await db
    .select()
    .from(payments)
    .where(eq(payments.stripeSessionId, sessionId))
    .limit(1);
  return rows[0] ? toEntity(rows[0]) : null;
}

/**
 * Update payment status and optionally set Stripe payment intent ID.
 * @param id - Payment UUID
 * @param status - New status value to write
 * @param stripePaymentIntentId - Stripe PaymentIntent ID to record (only set when provided)
 */
export async function updatePaymentStatus(
  id: string,
  status: string,
  stripePaymentIntentId?: string,
): Promise<void> {
  const updates: Record<string, unknown> = { status, updatedAt: new Date() };
  if (stripePaymentIntentId) updates.stripePaymentIntentId = stripePaymentIntentId;
  await db.update(payments).set(updates).where(eq(payments.id, id));
}

/**
 * CAS update: transition status from `fromStatus` to `toStatus`.
 * This is the idempotent guard for webhook replay.
 * @param id - Payment UUID
 * @param fromStatus - Status the row must currently be in for the update to apply
 * @param toStatus - Status to transition the row to
 * @param charged - What Stripe actually took, recorded in the same statement
 *   that moves the status so the two can never disagree.
 * @param charged.stripePaymentIntentId - The PaymentIntent behind the charge,
 *   which a refund needs.
 * @param charged.taxCents - The tax Stripe worked out.
 * @param charged.totalCents - Face value plus that tax: what the buyer paid,
 *   and what a refund pays back.
 * @param tx - The fulfillment transaction, when the caller has one.
 * @returns True if this call performed the transition (row was in `fromStatus`);
 *   false if another concurrent call already transitioned it
 */
export async function updatePaymentStatusCAS(
  id: string,
  fromStatus: readonly string[],
  toStatus: string,
  charged?: {
    stripePaymentIntentId?: string | undefined;
    taxCents?: number | undefined;
    totalCents?: number | undefined;
  },
  tx: DbTx | typeof db = db,
): Promise<boolean> {
  const updates: Record<string, unknown> = {
    status: toStatus,
    updatedAt: new Date(),
  };
  if (charged?.stripePaymentIntentId !== undefined) {
    updates.stripePaymentIntentId = charged.stripePaymentIntentId;
  }
  if (charged?.taxCents !== undefined) updates.taxCents = charged.taxCents;
  if (charged?.totalCents !== undefined) updates.totalCents = charged.totalCents;
  const result = await tx
    .update(payments)
    .set(updates)
    .where(and(eq(payments.id, id), inArray(payments.status, [...fromStatus])))
    .returning({ id: payments.id });
  return result.length > 0;
}

/**
 * List payments for a user, ordered by most recent.
 * @param userId - User whose payments to list
 * @param limit - Page size (capped at 100)
 * @param offset - Pagination offset
 * @returns The user's payment entities, newest first
 */
export async function listPaymentsByUser(
  userId: string,
  limit = 20,
  offset = 0,
): Promise<PaymentEntity[]> {
  const rows = await db
    .select()
    .from(payments)
    .where(eq(payments.userId, userId))
    .orderBy(desc(payments.createdAt))
    .limit(Math.min(limit, 100))
    .offset(offset);
  return rows.map(toEntity);
}

/** Everything one purchase's confirmation email states. */
export interface ConfirmationView {
  paymentId: string;
  email: string;
  locale: string;
  amountCents: number;
  taxCents: number | null;
  totalCents: number | null;
  currency: string;
  creditsGranted: number;
  /**
   * When the lot was opened. The refund window counts from here, and the
   * letter prints this same instant as the purchase time so the two dates a
   * buyer subtracts come from one column.
   */
  grantedAt: Date | null;
  consentTextVersion: string | null;
  refundTextVersion: string | null;
  /**
   * The buyer's IANA zone as their browser reported it at checkout. The
   * purchase time is printed in it, beside the same instant in UTC.
   */
  timeZone: string;
  /**
   * What the account holds right now. A resend says today's figure, which is
   * the one question in this letter whose answer moves.
   */
  balanceCredits: number;
}

/**
 * Read what one purchase's confirmation email needs.
 * @param paymentId - The purchase.
 * @returns The view, or null when no such payment exists.
 */
export async function getConfirmationView(
  paymentId: string,
): Promise<ConfirmationView | null> {
  const rows = await db
    .select({
      paymentId: payments.id,
      email: users.email,
      amountCents: payments.amountCents,
      taxCents: payments.taxCents,
      totalCents: payments.totalCents,
      currency: payments.currency,
      creditsGranted: payments.creditsGranted,
      metadata: payments.metadata,
      grantedAt: creditLots.createdAt,
      consentTextVersion: purchaseConsents.consentTextVersion,
      refundTextVersion: purchaseConsents.refundTextVersion,
    })
    .from(payments)
    .innerJoin(users, eq(users.id, payments.userId))
    .leftJoin(creditLots, eq(creditLots.paymentId, payments.id))
    .leftJoin(purchaseConsents, eq(purchaseConsents.paymentId, payments.id))
    .where(eq(payments.id, paymentId))
    .limit(1);
  const row = rows[0];
  if (!row) return null;

  const [held] = await db
    .select({ total: sql<number>`coalesce(sum(${creditLots.purchasedCredits}), 0)` })
    .from(creditLots)
    .where(
      and(
        eq(creditLots.userId, sql`(SELECT user_id FROM payments WHERE id = ${paymentId})`),
        isNull(creditLots.deletedAt),
      ),
    );

  const metadata = row.metadata ?? {};
  const locale = metadata["locale"];
  const timeZone = metadata["timeZone"];
  return {
    paymentId: row.paymentId,
    email: row.email,
    locale: typeof locale === "string" && locale.length > 0 ? locale : "en",
    timeZone:
      typeof timeZone === "string" && timeZone.length > 0 ? timeZone : "UTC",
    amountCents: row.amountCents,
    taxCents: row.taxCents,
    totalCents: row.totalCents,
    currency: row.currency,
    creditsGranted: row.creditsGranted,
    grantedAt: row.grantedAt,
    consentTextVersion: row.consentTextVersion,
    refundTextVersion: row.refundTextVersion,
    balanceCredits: Number(held?.total ?? 0),
  };
}
