// Copyright (c) 2026 Orime, Inc.
// SPDX-License-Identifier: LicenseRef-BSAL-1.0

/**
 * Payment repository — data access for the payments table.
 */

import { eq, and, desc, inArray, isNull, isNotNull, lt, or, sql } from "drizzle-orm";
import { db } from "@breatic/core";
import type { DbTx } from "@breatic/core";
import {
  payments,
  users,
  creditLots,
  purchaseConsents,
  purchaseMailOutbox,
  studios,
} from "@breatic/core";
import type { PaymentEntity } from "@breatic/shared";

/**
 * Map a raw `payments` table row to a `PaymentEntity` domain object,
 * defaulting a null `metadata` JSONB column to an empty object.
 * @param row - Raw row selected from the `payments` table
 * @returns The mapped payment entity
 */
function toEntity(row: typeof payments.$inferSelect): PaymentEntity {
  return {
    id: row.id,
    userId: row.userId,
    stripeSessionId: row.stripeSessionId,
    stripePaymentIntentId: row.stripePaymentIntentId,
    amountCents: row.amountCents,
    currency: row.currency,
    status: row.status,
    creditsGranted: row.creditsGranted,
    metadata: (row.metadata ?? {}),
    createdAt: row.createdAt,
    updatedAt: row.updatedAt,
  };
}

/**
 * Create a new payment record (status defaults to "pending" at the DB level).
 * @param data - Payment fields to insert
 * @param data.id - The row's id, generated by the caller before the Stripe
 *   session so the Back-button URL can carry it. Left out, the database picks one.
 * @param data.userId - User who initiated the purchase
 * @param data.stripeSessionId - Stripe Checkout session ID for this payment
 * @param data.amountCents - Charge amount in the smallest currency unit (cents)
 * @param data.creditsGranted - Number of credits granted once the payment completes
 * @param data.currency - ISO currency code (defaults to "usd")
 * @param data.metadata - Arbitrary JSONB metadata (defaults to an empty object)
 * @returns The inserted payment entity
 */
export async function createPayment(data: {
  id?: string;
  userId: string;
  stripeSessionId: string;
  amountCents: number;
  creditsGranted: number;
  currency?: string;
  metadata?: Record<string, unknown>;
}): Promise<PaymentEntity> {
  const rows = await db
    .insert(payments)
    .values({
      ...(data.id === undefined ? {} : { id: data.id }),
      userId: data.userId,
      stripeSessionId: data.stripeSessionId,
      amountCents: data.amountCents,
      creditsGranted: data.creditsGranted,
      currency: data.currency ?? "usd",
      metadata: data.metadata ?? {},
    })
    .returning();
  return toEntity(rows[0]!);
}

/**
 * Get a payment by ID.
 * @param id - Payment UUID
 * @returns The payment entity, or null if not found
 */
export async function getPaymentById(id: string): Promise<PaymentEntity | null> {
  const rows = await db.select().from(payments).where(eq(payments.id, id)).limit(1);
  return rows[0] ? toEntity(rows[0]) : null;
}

/**
 * Get a payment by Stripe session ID.
 * @param sessionId - Stripe Checkout session ID
 * @returns The payment entity, or null if no payment matches the session
 */
export async function getPaymentByStripeSessionId(sessionId: string): Promise<PaymentEntity | null> {
  const rows = await db
    .select()
    .from(payments)
    .where(eq(payments.stripeSessionId, sessionId))
    .limit(1);
  return rows[0] ? toEntity(rows[0]) : null;
}

/**
 * Update payment status and optionally set Stripe payment intent ID.
 * @param id - Payment UUID
 * @param status - New status value to write
 * @param stripePaymentIntentId - Stripe PaymentIntent ID to record (only set when provided)
 */
export async function updatePaymentStatus(
  id: string,
  status: string,
  stripePaymentIntentId?: string,
): Promise<void> {
  const updates: Record<string, unknown> = { status, updatedAt: new Date() };
  if (stripePaymentIntentId) updates.stripePaymentIntentId = stripePaymentIntentId;
  await db.update(payments).set(updates).where(eq(payments.id, id));
}

/**
 * CAS update: transition status from `fromStatus` to `toStatus`.
 * This is the idempotent guard for webhook replay.
 * @param id - Payment UUID
 * @param fromStatus - Status the row must currently be in for the update to apply
 * @param toStatus - Status to transition the row to
 * @param charged - What Stripe actually took, recorded in the same statement
 *   that moves the status so the two can never disagree.
 * @param charged.stripePaymentIntentId - The PaymentIntent behind the charge,
 *   which a refund needs.
 * @param charged.taxCents - The tax Stripe worked out.
 * @param charged.totalCents - Face value plus that tax. On this call the money
 *   has landed, so it is also what the buyer paid and what a refund pays
 *   back.
 * @param tx - The fulfillment transaction, when the caller has one.
 * @returns True if this call performed the transition (row was in `fromStatus`);
 *   false if another concurrent call already transitioned it
 */
export async function updatePaymentStatusCAS(
  id: string,
  fromStatus: readonly string[],
  toStatus: string,
  charged?: {
    stripePaymentIntentId?: string | undefined;
    taxCents?: number | undefined;
    totalCents?: number | undefined;
  },
  tx: DbTx | typeof db = db,
): Promise<boolean> {
  const updates: Record<string, unknown> = {
    status: toStatus,
    updatedAt: new Date(),
  };
  if (charged?.stripePaymentIntentId !== undefined) {
    updates.stripePaymentIntentId = charged.stripePaymentIntentId;
  }
  if (charged?.taxCents !== undefined) updates.taxCents = charged.taxCents;
  if (charged?.totalCents !== undefined) updates.totalCents = charged.totalCents;
  const result = await tx
    .update(payments)
    .set(updates)
    .where(and(eq(payments.id, id), inArray(payments.status, [...fromStatus])))
    .returning({ id: payments.id });
  return result.length > 0;
}

/**
 * Record what Stripe worked out, on a purchase still waiting for its money.
 *
 * A delayed payment method finishes the checkout — the buyer has typed their
 * address, so Stripe has worked out the tax and knows the final figure — while
 * the money itself is still clearing. The row stays `pending` until it lands,
 * and without this the figure Stripe already holds is thrown away and the
 * screen keeps showing the pre-tax face value.
 *
 * Only a `pending` row is written. A purchase that has ended — refused,
 * abandoned, or landed — is not waiting for anything, and reconciling reaches
 * `failed` rows too: without this condition a bank's refusal would leave the
 * figure sitting on a purchase nobody was charged for, and put it back every
 * time somebody opened the credits panel.
 * @param id - The purchase.
 * @param charged - What Stripe says it comes to.
 * @param charged.taxCents - The tax it worked out.
 * @param charged.totalCents - Face value plus that tax.
 */
export async function recordPendingCharge(
  id: string,
  charged: { taxCents?: number | undefined; totalCents?: number | undefined },
): Promise<void> {
  const updates: Record<string, unknown> = { updatedAt: new Date() };
  if (charged.taxCents !== undefined) updates.taxCents = charged.taxCents;
  if (charged.totalCents !== undefined) updates.totalCents = charged.totalCents;
  if (Object.keys(updates).length === 1) return;
  await db
    .update(payments)
    .set(updates)
    .where(and(eq(payments.id, id), eq(payments.status, "pending")));
}

/**
 * The payments one reconcile pass should ask Stripe about.
 *
 * Three bounds, each answering a different way this could go wrong.
 *
 * `pending` and `failed` both qualify: a payment that failed and was paid
 * afterwards reaches us through one webhook that can be lost, and reconciling
 * is the only other way that correction arrives.
 *
 * The age bound skips the buyer who is still on the Stripe page filling in a
 * card. That session is certainly unpaid, and asking about it spends a round
 * trip to learn nothing.
 *
 * Ordering by `updated_at` rather than by age is what stops the same rows
 * holding every slot. An abandoned checkout stays `pending` for the two hours
 * its session lives, and there can be many; taking the oldest first would let
 * a handful of them occupy all three places pass after pass, while the one
 * purchase that was actually paid never came up. Every pass touches
 * `updated_at` on what it looked at, so what it looked at goes to the back.
 * @param userId - The account whose purchases to repair.
 * @param batchSize - How many to take.
 * @param minAgeSeconds - How old they must be.
 * @returns Those payments, least recently looked at first.
 */
export async function listPaymentsToReconcile(
  userId: string,
  batchSize: number,
  minAgeSeconds: number,
): Promise<PaymentEntity[]> {
  const rows = await db
    .select()
    .from(payments)
    .where(
      and(
        eq(payments.userId, userId),
        inArray(payments.status, ["pending", "failed"]),
        // A row with no session is a row Stripe cannot be asked about. The
        // checkout path cannot produce one — the session exists before the
        // row does — but the column is nullable and a pass that picked such a
        // row up would hold a slot to retrieve nothing.
        isNotNull(payments.stripeSessionId),
        sql`${payments.createdAt} < now() - make_interval(secs => ${minAgeSeconds})`,
      ),
    )
    .orderBy(payments.updatedAt)
    .limit(batchSize);
  return rows.map(toEntity);
}

/**
 * Mark these payments as looked at, whatever the look found.
 *
 * This is the other half of the ordering above: without it, a pass that
 * changed nothing would leave the same rows at the front of the queue and
 * pick them again next time.
 * @param ids - The payments this pass asked Stripe about.
 */
export async function touchReconciled(ids: readonly string[]): Promise<void> {
  if (ids.length === 0) return;
  await db
    .update(payments)
    .set({ updatedAt: new Date() })
    .where(inArray(payments.id, [...ids]));
}

/** One row of the purchase history, straight off the join. */
export interface PurchaseHistoryRow {
  paymentId: string;
  amountCents: number;
  taxCents: number | null;
  totalCents: number | null;
  currency: string;
  creditsGranted: number;
  status: string;
  createdAt: Date;
  cursorAt: string;
  remainingCredits: string | null;
  lifecycle: string | null;
  designatedStudioId: string | null;
  designatedStudioName: string | null;
  mailStatus: string | null;
  mailUpdatedAt: Date | null;
}

/**
 * One keyset page of this account's purchases, newest first.
 *
 * Built from `payments` and joined outward, because a purchase that has not
 * landed has no lot: one still processing, one the buyer abandoned. Those are
 * the rows this screen exists to show, and starting from the lots would leave
 * them out entirely.
 *
 * The cursor is keyed on `payments` for the same reason. The lot's timestamp
 * and id are null on exactly those rows, so keying there would collapse the
 * ordering and the cursor together — paging to the end would hand back an
 * empty cursor and the older payments would become unreachable.
 *
 * The studio a purchase points at is read through a "not deleted" test, the
 * same one the overview applies. Without it one purchase counts as unassigned
 * in the overview and reads "assigned to X" here with X gone.
 * @param userId - Whose purchases.
 * @param limit - How many to take; one more is fetched to detect a next page.
 * @param cursor - The `(created_at, id)` of the previous page's last row.
 * @returns Those rows, one over the page size when more exist.
 */
export async function listPurchaseHistory(
  userId: string,
  limit: number,
  cursor: { createdAt: string; id: string } | null,
): Promise<PurchaseHistoryRow[]> {
  const at = cursor ? sql`${cursor.createdAt}::timestamptz` : null;
  const liveStudio = sql`CASE WHEN ${studios.deletedAt} IS NULL THEN`;
  return db
    .select({
      paymentId: payments.id,
      amountCents: payments.amountCents,
      taxCents: payments.taxCents,
      totalCents: payments.totalCents,
      currency: payments.currency,
      creditsGranted: payments.creditsGranted,
      status: payments.status,
      createdAt: payments.createdAt,
      // Full precision, carried as text: a cursor that went through `Date`
      // would lose the microseconds Postgres stores, and two purchases inside
      // one millisecond would straddle a page boundary and one would vanish.
      cursorAt: sql<string>`${payments.createdAt}::text`,
      remainingCredits: creditLots.remainingCredits,
      lifecycle: creditLots.lifecycle,
      designatedStudioId: sql<
        string | null
      >`${liveStudio} ${studios.id} ELSE NULL END`,
      designatedStudioName: sql<
        string | null
      >`${liveStudio} ${studios.name} ELSE NULL END`,
      mailStatus: purchaseMailOutbox.status,
      mailUpdatedAt: purchaseMailOutbox.updatedAt,
    })
    .from(payments)
    .leftJoin(
      creditLots,
      and(eq(creditLots.paymentId, payments.id), isNull(creditLots.deletedAt)),
    )
    .leftJoin(studios, eq(studios.id, creditLots.designatedStudioId))
    .leftJoin(purchaseMailOutbox, eq(purchaseMailOutbox.paymentId, payments.id))
    .where(
      and(
        eq(payments.userId, userId),
        at === null
          ? undefined
          : or(
              lt(payments.createdAt, at),
              and(eq(payments.createdAt, at), lt(payments.id, cursor!.id)),
            ),
      ),
    )
    .orderBy(desc(payments.createdAt), desc(payments.id))
    .limit(limit + 1);
}

/** Everything one purchase's confirmation email states. */
export interface ConfirmationView {
  paymentId: string;
  email: string;
  locale: string;
  amountCents: number;
  taxCents: number | null;
  totalCents: number | null;
  currency: string;
  creditsGranted: number;
  /**
   * When the lot was opened. The refund window counts from here, and the
   * letter prints this same instant as the purchase time so the two dates a
   * buyer subtracts come from one column.
   */
  grantedAt: Date | null;
  consentTextVersion: string | null;
  refundTextVersion: string | null;
  /**
   * The buyer's IANA zone as their browser reported it at checkout. The
   * purchase time is printed in it, beside the same instant in UTC.
   */
  timeZone: string;
  /**
   * What the account holds right now. A resend says today's figure, which is
   * the one question in this letter whose answer moves.
   */
  balanceCredits: number;
}

/**
 * Read what one purchase's confirmation email needs.
 * @param paymentId - The purchase.
 * @returns The view, or null when no such payment exists.
 */
export async function getConfirmationView(
  paymentId: string,
): Promise<ConfirmationView | null> {
  const rows = await db
    .select({
      paymentId: payments.id,
      email: users.email,
      amountCents: payments.amountCents,
      taxCents: payments.taxCents,
      totalCents: payments.totalCents,
      currency: payments.currency,
      creditsGranted: payments.creditsGranted,
      metadata: payments.metadata,
      grantedAt: creditLots.createdAt,
      consentTextVersion: purchaseConsents.consentTextVersion,
      refundTextVersion: purchaseConsents.refundTextVersion,
    })
    .from(payments)
    .innerJoin(users, eq(users.id, payments.userId))
    .leftJoin(creditLots, eq(creditLots.paymentId, payments.id))
    .leftJoin(purchaseConsents, eq(purchaseConsents.paymentId, payments.id))
    .where(eq(payments.id, paymentId))
    .limit(1);
  const row = rows[0];
  if (!row) return null;

  // What is left across this account's live lots, which is the same figure the
  // credits overlay puts at the top of every screen. A lot that has been spent
  // down still holds its purchased amount, and a refunded one holds it too, so
  // either column would answer "ever bought" to a letter that says "now".
  const [held] = await db
    .select({
      total: sql<number>`coalesce(sum(${creditLots.remainingCredits}), 0)`,
    })
    .from(creditLots)
    .where(
      and(
        eq(
          creditLots.userId,
          sql`(SELECT user_id FROM payments WHERE id = ${paymentId})`,
        ),
        eq(creditLots.lifecycle, "active"),
        isNull(creditLots.deletedAt),
      ),
    );

  const metadata = row.metadata ?? {};
  const locale = metadata["locale"];
  const timeZone = metadata["timeZone"];
  return {
    paymentId: row.paymentId,
    email: row.email,
    locale: typeof locale === "string" && locale.length > 0 ? locale : "en",
    timeZone:
      typeof timeZone === "string" && timeZone.length > 0 ? timeZone : "UTC",
    amountCents: row.amountCents,
    taxCents: row.taxCents,
    totalCents: row.totalCents,
    currency: row.currency,
    creditsGranted: row.creditsGranted,
    grantedAt: row.grantedAt,
    consentTextVersion: row.consentTextVersion,
    refundTextVersion: row.refundTextVersion,
    balanceCredits: Number(held?.total ?? 0),
  };
}
