// Copyright (c) 2026 Orime, Inc.
// SPDX-License-Identifier: LicenseRef-BSAL-1.0

/**
 * The storage keys a mini-tool container job writes (inner#888 §8.1 step 1).
 *
 * Each output gets the grant a backend upload gets, so the report that files
 * it finds one: generated by this task, announced by the worker rather than
 * by the report. The keys are the job's write permission, valid for as long
 * as the job may run.
 */

import { coverKeyFor, getStorageConfig } from "@breatic/core";
import type { MiniToolJobOutput, MiniToolOutput } from "@breatic/shared";

import { issueUploadGrant } from "@domain/asset/upload-grant.service.js";

/** How each output modality is stored. */
const STORED_AS: Readonly<Record<MiniToolOutput["modality"], { ext: string; contentType: string }>> = {
  image: { ext: ".png", contentType: "image/png" },
  video: { ext: ".mp4", contentType: "video/mp4" },
  audio: { ext: ".mp3", contentType: "audio/mpeg" },
  text: { ext: ".txt", contentType: "text/plain" },
};

/**
 * Open one grant per output, in output order.
 * @param params - The run.
 * @param params.projectId - The project the outputs belong to.
 * @param params.actingUserId - Who ran the tool.
 * @param params.taskId - The generation task the outputs are filed against.
 * @param params.deadlineAt - Epoch ms the job may run until.
 * @param params.outputs - The tool's declared outputs.
 * @returns What the job writes, with a cover key for each video.
 * @throws {NotFoundError} When the project does not exist or is soft-deleted.
 */
export async function openContainerOutputs(params: {
  projectId: string;
  actingUserId: string;
  taskId: string;
  deadlineAt: number;
  outputs: readonly MiniToolOutput[];
}): Promise<MiniToolJobOutput[]> {
  const { upload } = getStorageConfig();
  const opened: MiniToolJobOutput[] = [];
  for (const output of params.outputs) {
    const stored = STORED_AS[output.modality];
    const { key } = await issueUploadGrant({
      projectId: params.projectId,
      actingUserId: params.actingUserId,
      declaredSize: upload.max_upload_bytes,
      taskType: output.modality,
      ext: stored.ext,
      expiresAt: new Date(params.deadlineAt),
      context: { assetSource: "ai", generationTaskId: params.taskId, derived: true },
    });
    opened.push({
      storageKey: key,
      contentType: stored.contentType,
      ...(output.modality === "video" && { coverKey: coverKeyFor(key) }),
    });
  }
  return opened;
}
