// Copyright (c) 2026 Orime, Inc.
// SPDX-License-Identifier: LicenseRef-BSAL-1.0

/**
 * Where each message the product's screens show is in the product guide.
 *
 * Every message the canvas, document, project and notification screens can
 * show is either quoted by the guide, described by it, or left out for a
 * stated reason. A message the guide quotes needs no entry here; every other
 * one does, so a new message on those screens fails the coverage test until
 * someone decides where it belongs.
 */

/** Why a message is not in the guide. */
export const REASONS = {
  SCREEN_READER: "Only a screen reader announces it; the guide describes the control by how it looks.",
  VIEWERS_ONLY: "Only viewers see it, and viewers get no chat.",
  PASSING: "A loading or copied word that goes away by itself.",
  ECHO: "It confirms what the reader has just done.",
  SAYS_TRY_AGAIN: "A failure that already tells the reader to try again or reload; the guide has nothing to add.",
  READ_ONLY_PANEL: "Placeholder wording in the read-only panel, which the guide says does not show the space yet.",
  FILLS_A_VALUE: "A time, count, unit or name filled into a row; it reads as itself.",
  SAYS_WHAT_HAPPENED: "A message or list entry that says in its own words what happened.",
  NOT_OPEN: "A command in the document AI menu, which the guide says does nothing yet.",
  DEPLOYMENT: "Shown only on a deployment with no model provider configured.",
  SAYS_WHAT_TO_PICK: "A hover tip or the pick bar's prompt, which says itself what to pick.",
  EMPTY_OR_SEARCH: "An empty list saying it is empty, or a search box's placeholder.",
} as const;

/** The guide describes the message: this phrase is in it. */
interface Described {
  described: RegExp;
}

/** The guide leaves the message out, for this reason. */
interface Excluded {
  excluded: (typeof REASONS)[keyof typeof REASONS];
}

/** Every message the guide does not quote, and what the guide does with it. */
export const NOT_QUOTED: Readonly<Record<string, Described | Excluded>> = {
  "activity.description": { described: /the project's uploads, generations and changes to spaces and members/ },
  "activity.empty": { described: /the project's uploads, generations and changes to spaces and members/ },
  "activity.label": { excluded: REASONS.SCREEN_READER },
  "activity.loading": { excluded: REASONS.PASSING },
  "activity.relative.daysAgo": { excluded: REASONS.FILLS_A_VALUE },
  "activity.relative.hoursAgo": { excluded: REASONS.FILLS_A_VALUE },
  "activity.relative.isoDate": { excluded: REASONS.FILLS_A_VALUE },
  "activity.relative.justNow": { excluded: REASONS.FILLS_A_VALUE },
  "activity.relative.minutesAgo": { excluded: REASONS.FILLS_A_VALUE },
  "activity.relative.monthsAgo": { excluded: REASONS.FILLS_A_VALUE },
  "activity.relative.weeksAgo": { excluded: REASONS.FILLS_A_VALUE },
  "activity.relative.yesterday": { excluded: REASONS.FILLS_A_VALUE },
  "activity.type.assetDeleted": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "activity.type.assetUploaded": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "activity.type.assetUploadedAudio": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "activity.type.assetUploadedImage": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "activity.type.assetUploadedVideo": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "activity.type.generationFailed": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "activity.type.generationSucceeded": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "activity.type.generationSucceededAudio": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "activity.type.generationSucceededImage": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "activity.type.generationSucceededTool": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "activity.type.generationSucceededVideo": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "activity.type.memberJoined": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "activity.type.memberRemoved": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "activity.type.memberRoleChanged": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "activity.type.ownershipTransferred": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "activity.type.spaceCreated": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "activity.type.spaceDeleted": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "activity.type.spaceLocked": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "activity.type.spaceRenamed": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "activity.type.spaceRestored": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "activity.type.spaceUnlocked": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "canvas.annotation.cannotWrite": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "canvas.annotation.noteGone": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "canvas.annotation.targetGone": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "canvas.annotation.unknownAuthor": { excluded: REASONS.FILLS_A_VALUE },
  "canvas.connection.kind3d": { excluded: REASONS.FILLS_A_VALUE },
  "canvas.connection.kindAnnotation": { excluded: REASONS.FILLS_A_VALUE },
  "canvas.connection.kindAudio": { excluded: REASONS.FILLS_A_VALUE },
  "canvas.connection.kindGroup": { excluded: REASONS.FILLS_A_VALUE },
  "canvas.connection.kindImage": { excluded: REASONS.FILLS_A_VALUE },
  "canvas.connection.kindText": { excluded: REASONS.FILLS_A_VALUE },
  "canvas.connection.kindVideo": { excluded: REASONS.FILLS_A_VALUE },
  "canvas.connection.kindWeb": { excluded: REASONS.FILLS_A_VALUE },
  "canvas.connection.rejected": { described: /snaps back with a message naming the two kinds/ },
  "canvas.contextMenu.clipboardError": { excluded: REASONS.SAYS_TRY_AGAIN },
  "canvas.emptyImage.color.custom": { excluded: REASONS.SCREEN_READER },
  "canvas.emptyImage.execute": { excluded: REASONS.SCREEN_READER },
  "canvas.emptyImage.exit": { excluded: REASONS.SCREEN_READER },
  "canvas.emptyImage.generateFailed": { excluded: REASONS.SAYS_TRY_AGAIN },
  "canvas.generatePanel.audioDialogueSummary": { excluded: REASONS.FILLS_A_VALUE },
  "canvas.generatePanel.audioLanguageSearch": { excluded: REASONS.EMPTY_OR_SEARCH },
  "canvas.generatePanel.audioOptionEmpty": { excluded: REASONS.EMPTY_OR_SEARCH },
  "canvas.generatePanel.audioPromptPlaceholder": { described: /Then the prompt box/ },
  "canvas.generatePanel.audioReadingDialogue": { described: /or a dialogue for a number of speakers/ },
  "canvas.generatePanel.catalogNoModels": { excluded: REASONS.DEPLOYMENT },
  "canvas.generatePanel.characterImageTip": { excluded: REASONS.SAYS_WHAT_TO_PICK },
  "canvas.generatePanel.coverSongTip": { excluded: REASONS.SAYS_WHAT_TO_PICK },
  "canvas.generatePanel.creditsPerThousandChars": { excluded: REASONS.FILLS_A_VALUE },
  "canvas.generatePanel.drivingAudioTip": { excluded: REASONS.SAYS_WHAT_TO_PICK },
  "canvas.generatePanel.drivingVideoTip": { excluded: REASONS.SAYS_WHAT_TO_PICK },
  "canvas.generatePanel.durationSeconds": { excluded: REASONS.FILLS_A_VALUE },
  "canvas.generatePanel.endFrameTip": { excluded: REASONS.SAYS_WHAT_TO_PICK },
  "canvas.generatePanel.errorNoCharacterImage": { described: /A required slot left empty stops the run with a message naming it/ },
  "canvas.generatePanel.errorNoDrivingAudio": { described: /A required slot left empty stops the run with a message naming it/ },
  "canvas.generatePanel.errorNoDrivingVideo": { described: /A required slot left empty stops the run with a message naming it/ },
  "canvas.generatePanel.errorNoEndFrame": { described: /A required slot left empty stops the run with a message naming it/ },
  "canvas.generatePanel.errorNoLeftAudio": { described: /A required slot left empty stops the run with a message naming it/ },
  "canvas.generatePanel.errorNoMusicSong": { described: /A required slot left empty stops the run with a message naming it/ },
  "canvas.generatePanel.errorNoRefAudio": { described: /A required slot left empty stops the run with a message naming it/ },
  "canvas.generatePanel.errorNoReferenceMention": { described: /A video model that needs one says what is still missing/ },
  "canvas.generatePanel.errorNoRightAudio": { described: /A required slot left empty stops the run with a message naming it/ },
  "canvas.generatePanel.errorNoSourceVideo": { described: /A required slot left empty stops the run with a message naming it/ },
  "canvas.generatePanel.errorTooManyReferences": { described: /takes at most so many mentions of a kind; past that, pressing generate says the limit/ },
  "canvas.generatePanel.execute": { excluded: REASONS.SCREEN_READER },
  "canvas.generatePanel.exit": { excluded: REASONS.SCREEN_READER },
  "canvas.generatePanel.firstFrameTip": { excluded: REASONS.SAYS_WHAT_TO_PICK },
  "canvas.generatePanel.focusCropDiscarded": { described: /If the source node changes, is still processing or is deleted while you pick, the box is cleared and a message says what happened/ },
  "canvas.generatePanel.focusCropTag": { excluded: REASONS.SCREEN_READER },
  "canvas.generatePanel.focusSourceBusy": { described: /If the source node changes, is still processing or is deleted while you pick, the box is cleared and a message says what happened/ },
  "canvas.generatePanel.focusSourceBusyByPeer": { described: /If the source node changes, is still processing or is deleted while you pick, the box is cleared and a message says what happened/ },
  "canvas.generatePanel.focusSourceDeleted": { described: /If the source node changes, is still processing or is deleted while you pick, the box is cleared and a message says what happened/ },
  "canvas.generatePanel.focusSourceDeletedByPeer": { described: /If the source node changes, is still processing or is deleted while you pick, the box is cleared and a message says what happened/ },
  "canvas.generatePanel.focusSourceFailed": { described: /If the source node changes, is still processing or is deleted while you pick, the box is cleared and a message says what happened/ },
  "canvas.generatePanel.focusSourceReplaced": { described: /If the source node changes, is still processing or is deleted while you pick, the box is cleared and a message says what happened/ },
  "canvas.generatePanel.focusSourceReplacedByPeer": { described: /If the source node changes, is still processing or is deleted while you pick, the box is cleared and a message says what happened/ },
  "canvas.generatePanel.focusSourceUnavailable": { described: /If the source node changes, is still processing or is deleted while you pick, the box is cleared and a message says what happened/ },
  "canvas.generatePanel.focusTimelineLabel": { excluded: REASONS.SCREEN_READER },
  "canvas.generatePanel.focusTip": { excluded: REASONS.SAYS_WHAT_TO_PICK },
  "canvas.generatePanel.focusUploadFailed": { excluded: REASONS.SAYS_TRY_AGAIN },
  "canvas.generatePanel.insertFocusCropNamed": { excluded: REASONS.SCREEN_READER },
  "canvas.generatePanel.insertReferenceNamed": { excluded: REASONS.SCREEN_READER },
  "canvas.generatePanel.itemsRemove": { excluded: REASONS.SCREEN_READER },
  "canvas.generatePanel.leftAudioTip": { excluded: REASONS.SAYS_WHAT_TO_PICK },
  "canvas.generatePanel.locateSource": { excluded: REASONS.SCREEN_READER },
  "canvas.generatePanel.mentionNoMatch": { excluded: REASONS.EMPTY_OR_SEARCH },
  "canvas.generatePanel.moodImageTip": { excluded: REASONS.SAYS_WHAT_TO_PICK },
  "canvas.generatePanel.musicLyricsPlaceholder": { described: /Then the prompt box/ },
  "canvas.generatePanel.musicMelodyTip": { excluded: REASONS.SAYS_WHAT_TO_PICK },
  "canvas.generatePanel.musicPromptPlaceholder": { described: /Then the prompt box/ },
  "canvas.generatePanel.musicSongTip": { excluded: REASONS.SAYS_WHAT_TO_PICK },
  "canvas.generatePanel.musicVocalTip": { excluded: REASONS.SAYS_WHAT_TO_PICK },
  "canvas.generatePanel.promptPlaceholder": { described: /Then the prompt box/ },
  "canvas.generatePanel.refAudioTip": { excluded: REASONS.SAYS_WHAT_TO_PICK },
  "canvas.generatePanel.referenceAddFailed": { excluded: REASONS.SAYS_TRY_AGAIN },
  "canvas.generatePanel.referencePoolFull": { described: /past it a new one is refused with a message naming the limit/ },
  "canvas.generatePanel.referenceTip": { excluded: REASONS.SAYS_WHAT_TO_PICK },
  "canvas.generatePanel.referenceTipAudio": { excluded: REASONS.SAYS_WHAT_TO_PICK },
  "canvas.generatePanel.refuseInsertTypeUnused": { described: /a faded chip shows a message saying why instead/ },
  "canvas.generatePanel.removeCharacterImage": { excluded: REASONS.SCREEN_READER },
  "canvas.generatePanel.removeDrivingAudio": { excluded: REASONS.SCREEN_READER },
  "canvas.generatePanel.removeDrivingVideo": { excluded: REASONS.SCREEN_READER },
  "canvas.generatePanel.removeEndFrame": { excluded: REASONS.SCREEN_READER },
  "canvas.generatePanel.removeFirstFrame": { excluded: REASONS.SCREEN_READER },
  "canvas.generatePanel.removeFocusCropNamed": { excluded: REASONS.SCREEN_READER },
  "canvas.generatePanel.removeLeftAudio": { excluded: REASONS.SCREEN_READER },
  "canvas.generatePanel.removeMoodImage": { excluded: REASONS.SCREEN_READER },
  "canvas.generatePanel.removeMusicMelody": { excluded: REASONS.SCREEN_READER },
  "canvas.generatePanel.removeMusicSong": { excluded: REASONS.SCREEN_READER },
  "canvas.generatePanel.removeMusicVocal": { excluded: REASONS.SCREEN_READER },
  "canvas.generatePanel.removeRefAudio": { excluded: REASONS.SCREEN_READER },
  "canvas.generatePanel.removeReferenceNamed": { excluded: REASONS.SCREEN_READER },
  "canvas.generatePanel.removeRightAudio": { excluded: REASONS.SCREEN_READER },
  "canvas.generatePanel.removeSourceVideo": { excluded: REASONS.SCREEN_READER },
  "canvas.generatePanel.removeStyle": { excluded: REASONS.SCREEN_READER },
  "canvas.generatePanel.rightAudioTip": { excluded: REASONS.SAYS_WHAT_TO_PICK },
  "canvas.generatePanel.selectCharacterImageFromCanvas": { excluded: REASONS.SAYS_WHAT_TO_PICK },
  "canvas.generatePanel.selectCoverSongFromCanvas": { excluded: REASONS.SAYS_WHAT_TO_PICK },
  "canvas.generatePanel.selectDrivingAudioFromCanvas": { excluded: REASONS.SAYS_WHAT_TO_PICK },
  "canvas.generatePanel.selectDrivingVideoFromCanvas": { excluded: REASONS.SAYS_WHAT_TO_PICK },
  "canvas.generatePanel.selectEndFrameFromCanvas": { excluded: REASONS.SAYS_WHAT_TO_PICK },
  "canvas.generatePanel.selectFocusFromCanvas": { excluded: REASONS.SAYS_WHAT_TO_PICK },
  "canvas.generatePanel.selectFromCanvas": { excluded: REASONS.SAYS_WHAT_TO_PICK },
  "canvas.generatePanel.selectLeftAudioFromCanvas": { excluded: REASONS.SAYS_WHAT_TO_PICK },
  "canvas.generatePanel.selectMoodImageFromCanvas": { excluded: REASONS.SAYS_WHAT_TO_PICK },
  "canvas.generatePanel.selectMusicMelodyFromCanvas": { excluded: REASONS.SAYS_WHAT_TO_PICK },
  "canvas.generatePanel.selectMusicSongFromCanvas": { excluded: REASONS.SAYS_WHAT_TO_PICK },
  "canvas.generatePanel.selectMusicVocalFromCanvas": { excluded: REASONS.SAYS_WHAT_TO_PICK },
  "canvas.generatePanel.selectRefAudioFromCanvas": { excluded: REASONS.SAYS_WHAT_TO_PICK },
  "canvas.generatePanel.selectRightAudioFromCanvas": { excluded: REASONS.SAYS_WHAT_TO_PICK },
  "canvas.generatePanel.selectSoundVideoFromCanvas": { excluded: REASONS.SAYS_WHAT_TO_PICK },
  "canvas.generatePanel.selectSourceVideoFromCanvas": { excluded: REASONS.SAYS_WHAT_TO_PICK },
  "canvas.generatePanel.selectStyleFromCanvas": { excluded: REASONS.SAYS_WHAT_TO_PICK },
  "canvas.generatePanel.sfxDurationSeconds": { excluded: REASONS.FILLS_A_VALUE },
  "canvas.generatePanel.sfxPromptPlaceholder": { described: /Then the prompt box/ },
  "canvas.generatePanel.sourceVideoTip": { excluded: REASONS.SAYS_WHAT_TO_PICK },
  "canvas.generatePanel.styleTip": { excluded: REASONS.SAYS_WHAT_TO_PICK },
  "canvas.generatePanel.videoPromptPlaceholder": { described: /Then the prompt box/ },
  "canvas.generatePanel.voiceEmpty": { excluded: REASONS.EMPTY_OR_SEARCH },
  "canvas.generatePanel.voiceLoading": { excluded: REASONS.PASSING },
  "canvas.generatePanel.voiceMoreError": { excluded: REASONS.SAYS_TRY_AGAIN },
  "canvas.generatePanel.voiceSample": { excluded: REASONS.SCREEN_READER },
  "canvas.group.background": { excluded: REASONS.SCREEN_READER },
  "canvas.group.backgroundBlue": { described: /a no-colour dot and seven colours/ },
  "canvas.group.backgroundGreen": { described: /a no-colour dot and seven colours/ },
  "canvas.group.backgroundNone": { described: /a no-colour dot and seven colours/ },
  "canvas.group.backgroundOrange": { described: /a no-colour dot and seven colours/ },
  "canvas.group.backgroundPink": { described: /a no-colour dot and seven colours/ },
  "canvas.group.backgroundRed": { described: /a no-colour dot and seven colours/ },
  "canvas.group.backgroundTeal": { described: /a no-colour dot and seven colours/ },
  "canvas.group.backgroundViolet": { described: /a no-colour dot and seven colours/ },
  "canvas.history.close": { excluded: REASONS.SCREEN_READER },
  "canvas.history.count": { excluded: REASONS.FILLS_A_VALUE },
  "canvas.history.snapshotEmpty": { described: /greyed while the node is empty/ },
  "canvas.history.snapshotFailed": { excluded: REASONS.SAYS_TRY_AGAIN },
  "canvas.minimap.label": { excluded: REASONS.SCREEN_READER },
  "canvas.task.countTip": { excluded: REASONS.FILLS_A_VALUE },
  "canvas.task.dismissFailed": { excluded: REASONS.SAYS_TRY_AGAIN },
  "canvas.task.elapsed": { excluded: REASONS.FILLS_A_VALUE },
  "canvas.task.endedAt": { excluded: REASONS.FILLS_A_VALUE },
  "canvas.task.failure.understand_over_cap": { described: /larger than a reading takes, or of a type it cannot read/ },
  "canvas.task.failure.understand_unsupported_type": { described: /larger than a reading takes, or of a type it cannot read/ },
  "canvas.task.panelClose": { excluded: REASONS.SCREEN_READER },
  "canvas.task.panelEmpty": { excluded: REASONS.EMPTY_OR_SEARCH },
  "canvas.task.panelError": { excluded: REASONS.SAYS_TRY_AGAIN },
  "canvas.task.panelLoading": { excluded: REASONS.PASSING },
  "canvas.task.panelReload": { excluded: REASONS.SAYS_TRY_AGAIN },
  "canvas.task.remaining": { excluded: REASONS.FILLS_A_VALUE },
  "canvas.task.startedAt": { excluded: REASONS.FILLS_A_VALUE },
  "canvas.upload.failed": { excluded: REASONS.SAYS_TRY_AGAIN },
  "canvas.upload.hashUnavailable": { excluded: REASONS.SAYS_TRY_AGAIN },
  "canvas.upload.unsupportedType": { described: /in a format that is not supported, or over the size limit, makes no node, and a message names it/ },
  "chat.action.copied": { excluded: REASONS.PASSING },
  "chat.action.copy": { excluded: REASONS.SCREEN_READER },
  "chat.assets.more": { excluded: REASONS.FILLS_A_VALUE },
  "chat.attachment.kind": { excluded: REASONS.FILLS_A_VALUE },
  "chat.attachment.more": { excluded: REASONS.FILLS_A_VALUE },
  "chat.attachment.nodes": { excluded: REASONS.FILLS_A_VALUE },
  "chat.backToLatest": { excluded: REASONS.SCREEN_READER },
  "chat.code.copy": { excluded: REASONS.SCREEN_READER },
  "chat.composer.atLimit": { described: /at the limit a line above the box says so/ },
  "chat.composer.attach": { excluded: REASONS.SCREEN_READER },
  "chat.composer.attachFull": { described: /is said on a line beside the plus sign/ },
  "chat.composer.attachTooLarge": { described: /is said on a line beside the plus sign/ },
  "chat.composer.attachUnavailable": { described: /is said on a line beside the plus sign/ },
  "chat.composer.attachUnsupported": { described: /is said on a line beside the plus sign/ },
  "chat.composer.attachmentFailed": { described: /could not be uploaded or read shows a red mark and says why/ },
  "chat.composer.attachmentUploading": { excluded: REASONS.SCREEN_READER },
  "chat.composer.chipsAria": { excluded: REASONS.SCREEN_READER },
  "chat.composer.inputAria": { excluded: REASONS.SCREEN_READER },
  "chat.composer.removeAttachment": { excluded: REASONS.SCREEN_READER },
  "chat.composer.sending": { excluded: REASONS.SCREEN_READER },
  "chat.conversation.rowActions": { excluded: REASONS.SCREEN_READER },
  "chat.empty.greetingDefault": { excluded: REASONS.FILLS_A_VALUE },
  "chat.empty.greetingWithName": { excluded: REASONS.FILLS_A_VALUE },
  "chat.history.description": { excluded: REASONS.SCREEN_READER },
  "chat.history.loading": { excluded: REASONS.PASSING },
  "chat.history.loadingMore": { excluded: REASONS.PASSING },
  "chat.load.failedBody": { excluded: REASONS.SAYS_TRY_AGAIN },
  "chat.markdown.backToReference": { excluded: REASONS.FILLS_A_VALUE },
  "chat.markdown.footnotes": { excluded: REASONS.FILLS_A_VALUE },
  "chat.markdown.taskDone": { excluded: REASONS.SCREEN_READER },
  "chat.markdown.taskTodo": { excluded: REASONS.SCREEN_READER },
  "chat.message.waiting": { excluded: REASONS.SCREEN_READER },
  "chat.relative.daysAgo": { excluded: REASONS.FILLS_A_VALUE },
  "chat.relative.hoursAgo": { excluded: REASONS.FILLS_A_VALUE },
  "chat.relative.isoDate": { excluded: REASONS.FILLS_A_VALUE },
  "chat.relative.justNow": { excluded: REASONS.FILLS_A_VALUE },
  "chat.relative.minutesAgo": { excluded: REASONS.FILLS_A_VALUE },
  "chat.relative.monthsAgo": { excluded: REASONS.FILLS_A_VALUE },
  "chat.relative.weeksAgo": { excluded: REASONS.FILLS_A_VALUE },
  "chat.relative.yesterday": { excluded: REASONS.FILLS_A_VALUE },
  "chat.sources.count": { described: /a button showing a word and how many sources there are/ },
  "chat.thinkingFor": { described: /afterwards how long it took/ },
  "chat.tool.running": { described: /a line may name what it is doing/ },
  "chrome.aria.agentColumnWidth": { excluded: REASONS.SCREEN_READER },
  "chrome.aria.backToStudio": { excluded: REASONS.SCREEN_READER },
  "chrome.aria.creditsBalance": { excluded: REASONS.SCREEN_READER },
  "chrome.aria.home": { excluded: REASONS.SCREEN_READER },
  "chrome.aria.openSpaces": { excluded: REASONS.SCREEN_READER },
  "chrome.aria.scrollTabsLeft": { excluded: REASONS.SCREEN_READER },
  "chrome.aria.scrollTabsRight": { excluded: REASONS.SCREEN_READER },
  "chrome.aria.spacesToolbar": { excluded: REASONS.SCREEN_READER },
  "chrome.tooltip.agentHide": { excluded: REASONS.SCREEN_READER },
  "chrome.tooltip.agentShow": { excluded: REASONS.SCREEN_READER },
  "chrome.tooltip.newConversation": { excluded: REASONS.SCREEN_READER },
  "chrome.tooltip.newSpace": { excluded: REASONS.SCREEN_READER },
  "chrome.tooltip.notifications": { excluded: REASONS.SCREEN_READER },
  "chrome.tooltip.openHistory": { excluded: REASONS.SCREEN_READER },
  "chrome.tooltip.revealActiveTab": { excluded: REASONS.SCREEN_READER },
  "chrome.tooltip.share": { excluded: REASONS.SCREEN_READER },
  "common.clipboardError": { excluded: REASONS.SAYS_TRY_AGAIN },
  "members.modal.description": { described: /There each member's row has a list to change their role/ },
  "members.modal.isMe": { excluded: REASONS.FILLS_A_VALUE },
  "members.modal.membersSection": { excluded: REASONS.FILLS_A_VALUE },
  "members.modal.removeConfirmBody": { described: /which asks .* first/ },
  "members.modal.removeFailed": { excluded: REASONS.SAYS_TRY_AGAIN },
  "members.modal.removeSuccess": { excluded: REASONS.ECHO },
  "members.modal.roleChangeFailed": { excluded: REASONS.SAYS_TRY_AGAIN },
  "members.modal.roleChanged": { excluded: REASONS.ECHO },
  "members.modal.roleSelectAria": { excluded: REASONS.SCREEN_READER },
  "members.modal.transferFailed": { excluded: REASONS.SAYS_TRY_AGAIN },
  "members.modal.transferHint": { described: /Nothing changes until that member accepts/ },
  "members.modal.transferPending": { described: /says it is waiting for them/ },
  "members.modal.transferPendingUnnamed": { described: /says it is waiting for them/ },
  "members.modal.transferSuccess": { excluded: REASONS.ECHO },
  "members.modal.transferWithdrawFailed": { excluded: REASONS.SAYS_TRY_AGAIN },
  "members.modal.transferWithdrawn": { excluded: REASONS.ECHO },
  "members.popover.isMe": { excluded: REASONS.FILLS_A_VALUE },
  "members.stack.triggerAria": { excluded: REASONS.SCREEN_READER },
  "menu.createAria": { excluded: REASONS.SCREEN_READER },
  "menu.disabledTooltip": { excluded: REASONS.VIEWERS_ONLY },
  "notifications.actorFallback": { excluded: REASONS.FILLS_A_VALUE },
  "notifications.empty": { excluded: REASONS.EMPTY_OR_SEARCH },
  "notifications.headline.membershipEnded": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "notifications.headline.membershipUpgradeIncomplete": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "notifications.headline.membershipUpgradeIncompleteNoPeriod": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "notifications.headline.storageQuotaExceeded": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "notifications.loading": { excluded: REASONS.PASSING },
  "notifications.subtitle.invitedAsEditor": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "notifications.subtitle.invitedAsGuest": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "notifications.subtitle.invitedAsMaintainer": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "notifications.subtitle.invitedAsViewer": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "notifications.subtitle.projectTransferHint": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "notifications.subtitle.studioTransferHint": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "project.header.renameFailed": { excluded: REASONS.SAYS_TRY_AGAIN },
  "project.space.error.create": { excluded: REASONS.SAYS_TRY_AGAIN },
  "project.space.error.notSynced": { excluded: REASONS.SAYS_TRY_AGAIN },
  "project.space.error.unreachable": { excluded: REASONS.SAYS_TRY_AGAIN },
  "project.space.timeout.create": { excluded: REASONS.SAYS_TRY_AGAIN },
  "project.space.timeout.retry": { excluded: REASONS.SAYS_TRY_AGAIN },
  "role.viewer": { excluded: REASONS.VIEWERS_ONLY },
  "roleTag.upgradeRequest.ariaLabel": { excluded: REASONS.VIEWERS_ONLY },
  "roleTag.upgradeRequest.description": { excluded: REASONS.VIEWERS_ONLY },
  "roleTag.upgradeRequest.pendingAriaLabel": { excluded: REASONS.VIEWERS_ONLY },
  "roleTag.upgradeRequest.pendingDescription": { excluded: REASONS.VIEWERS_ONLY },
  "roleTag.upgradeRequest.pendingTitle": { excluded: REASONS.VIEWERS_ONLY },
  "roleTag.upgradeRequest.placeholder": { excluded: REASONS.VIEWERS_ONLY },
  "roleTag.upgradeRequest.sending": { excluded: REASONS.VIEWERS_ONLY },
  "roleTag.upgradeRequest.submit": { excluded: REASONS.VIEWERS_ONLY },
  "roleTag.upgradeRequest.title": { excluded: REASONS.VIEWERS_ONLY },
  "roleTag.upgradeRequest.toast.failed": { excluded: REASONS.VIEWERS_ONLY },
  "roleTag.upgradeRequest.toast.sent": { excluded: REASONS.VIEWERS_ONLY },
  "roleTag.upgradeRequest.toast.withdrawFailed": { excluded: REASONS.VIEWERS_ONLY },
  "roleTag.upgradeRequest.toast.withdrawn": { excluded: REASONS.VIEWERS_ONLY },
  "roleTag.upgradeRequest.withdraw": { excluded: REASONS.VIEWERS_ONLY },
  "roleTag.upgradeRequest.withdrawing": { excluded: REASONS.VIEWERS_ONLY },
  "server.error.rate_limited": { excluded: REASONS.SAYS_TRY_AGAIN },
  "server.error.validation": { excluded: REASONS.SAYS_TRY_AGAIN },
  "share.copyInviteLink": { excluded: REASONS.SCREEN_READER },
  "share.inviteFailed": { excluded: REASONS.SAYS_TRY_AGAIN },
  "share.inviteLinkCopied": { excluded: REASONS.ECHO },
  "share.inviteLinkCopyFailed": { excluded: REASONS.SAYS_TRY_AGAIN },
  "share.inviteSending": { excluded: REASONS.PASSING },
  "share.inviteSent": { excluded: REASONS.ECHO },
  "spaces.create.description": { described: /type a name under/ },
  "spaces.create.namePlaceholder": { described: /type a name under/ },
  "spaces.create.nameRemaining": { excluded: REASONS.FILLS_A_VALUE },
  "spaces.document.blockHandle.dragTip": { excluded: REASONS.SCREEN_READER },
  "spaces.document.commands.aiOtherGroup": { excluded: REASONS.NOT_OPEN },
  "spaces.document.commands.aiProduceGroup": { excluded: REASONS.NOT_OPEN },
  "spaces.document.commands.aiRewriteGroup": { excluded: REASONS.NOT_OPEN },
  "spaces.document.commands.ai_custom": { excluded: REASONS.NOT_OPEN },
  "spaces.document.commands.ai_expand": { excluded: REASONS.NOT_OPEN },
  "spaces.document.commands.ai_illustrate": { excluded: REASONS.NOT_OPEN },
  "spaces.document.commands.ai_refine": { excluded: REASONS.NOT_OPEN },
  "spaces.document.commands.ai_shorten": { excluded: REASONS.NOT_OPEN },
  "spaces.document.commands.ai_storyboard": { excluded: REASONS.NOT_OPEN },
  "spaces.document.commands.ai_tone": { excluded: REASONS.NOT_OPEN },
  "spaces.document.commands.ai_translate": { excluded: REASONS.NOT_OPEN },
  "spaces.document.commands.bold": { excluded: REASONS.SCREEN_READER },
  "spaces.document.commands.code": { excluded: REASONS.SCREEN_READER },
  "spaces.document.commands.comingLabel": { described: /marked not open yet/ },
  "spaces.document.commands.italic": { excluded: REASONS.SCREEN_READER },
  "spaces.document.commands.link": { excluded: REASONS.SCREEN_READER },
  "spaces.document.commands.strike": { excluded: REASONS.SCREEN_READER },
  "spaces.document.commands.underline": { excluded: REASONS.SCREEN_READER },
  "spaces.document.docMenu.label": { excluded: REASONS.SCREEN_READER },
  "spaces.document.schemaOutdated.published": { excluded: REASONS.FILLS_A_VALUE },
  "spaces.document.schemaOutdated.riskUploads": { described: /a page older than the document editor shows/ },
  "spaces.document.schemaOutdated.risksLead": { described: /a page older than the document editor shows/ },
  "spaces.drawer.action.deleteConfirmDescription": { described: /which asks whether to delete the space by name/ },
  "spaces.drawer.action.deleteConfirmTitle": { described: /which asks whether to delete the space by name/ },
  "spaces.drawer.action.deleteFail": { excluded: REASONS.SAYS_TRY_AGAIN },
  "spaces.drawer.action.lockFail": { excluded: REASONS.SAYS_TRY_AGAIN },
  "spaces.drawer.action.operationFail": { excluded: REASONS.SAYS_TRY_AGAIN },
  "spaces.drawer.action.unlockFail": { excluded: REASONS.SAYS_TRY_AGAIN },
  "spaces.drawer.description": { excluded: REASONS.FILLS_A_VALUE },
  "spaces.drawer.empty": { excluded: REASONS.EMPTY_OR_SEARCH },
  "spaces.drawer.label": { excluded: REASONS.SCREEN_READER },
  "spaces.drawer.openAria": { excluded: REASONS.SCREEN_READER },
  "spaces.kind.timeline": { described: /a third, greyed card is not available yet/ },
  "spaces.lockedAria": { excluded: REASONS.SCREEN_READER },
  "spaces.readonly.canvas.description": { excluded: REASONS.READ_ONLY_PANEL },
  "spaces.readonly.canvas.title": { excluded: REASONS.READ_ONLY_PANEL },
  "spaces.readonly.description": { excluded: REASONS.READ_ONLY_PANEL },
  "spaces.readonly.document.description": { excluded: REASONS.READ_ONLY_PANEL },
  "spaces.readonly.document.title": { excluded: REASONS.READ_ONLY_PANEL },
  "spaces.readonly.label": { excluded: REASONS.READ_ONLY_PANEL },
  "spaces.readonly.timeline.description": { excluded: REASONS.READ_ONLY_PANEL },
  "spaces.readonly.timeline.title": { excluded: REASONS.READ_ONLY_PANEL },
  "spaces.rename.error.failed": { excluded: REASONS.SAYS_TRY_AGAIN },
  "spaces.rename.inputAriaLabel": { excluded: REASONS.SCREEN_READER },
  "spaces.tab.closeAria": { excluded: REASONS.SCREEN_READER },
  "viewportToolbar.aria": { excluded: REASONS.SCREEN_READER },
  "viewportToolbar.fitAria": { excluded: REASONS.SCREEN_READER },
  "viewportToolbar.minimap.hide": { excluded: REASONS.SCREEN_READER },
  "viewportToolbar.minimap.show": { excluded: REASONS.SCREEN_READER },
  "viewportToolbar.snap.off": { excluded: REASONS.SCREEN_READER },
  "viewportToolbar.snap.on": { excluded: REASONS.SCREEN_READER },
  "viewportToolbar.zoomCustomAria": { excluded: REASONS.SCREEN_READER },
  "viewportToolbar.zoomResetAria": { excluded: REASONS.SCREEN_READER },
};
