// Copyright (c) 2026 Orime, Inc.
// SPDX-License-Identifier: LicenseRef-BSAL-1.0

/**
 * Where each message the product's screens show is in the product guide.
 *
 * Every message the reader's screens can show is either quoted by the guide,
 * described by it, or left out for a stated reason. A message the guide
 * quotes needs no entry here; every other one does, so a new message on those
 * screens fails the coverage test until someone decides where it belongs.
 */

/** Why a message is not in the guide. */
export const REASONS = {
  SCREEN_READER: "Only a screen reader announces it; the guide describes the control by how it looks.",
  VIEWERS_ONLY: "Only viewers see it, and viewers get no chat.",
  OUTSIDERS_ONLY: "Only someone who is not a member of the project sees it, and they get no chat.",
  PASSING: "A loading or in-progress word that goes away by itself.",
  ECHO: "It confirms what the reader has just done.",
  SAYS_TRY_AGAIN: "A failure that already tells the reader to try again or reload; the guide has nothing to add.",
  READ_ONLY_PANEL: "Placeholder wording in the read-only panel, which the guide says does not show the space yet.",
  FILLS_A_VALUE: "A time, count, unit, label or name filled into a row; it reads as itself.",
  SAYS_WHAT_HAPPENED: "A message or list entry that says in its own words what happened.",
  SAYS_WHAT_TO_TYPE: "A box's placeholder or a suggestion, which says itself what to type.",
  MODEL_SETTING_NAME: "The name of one model's own setting on its row; the guide says such settings appear.",
  NOT_CREATABLE: "Belongs to a node type the reader cannot make.",
  NOT_USED: "Reached only by a key built at run time, and nothing builds this one.",
  NOT_ON_THESE_SCREENS: "Shown on a page outside the project, which the guide does not cover.",
  NOT_OPEN: "A command in the document AI menu, which the guide says does nothing yet.",
  DEPLOYMENT: "Shown only on a deployment with no model provider configured.",
  SAYS_WHAT_TO_PICK: "A hover tip or the pick bar's prompt, which says itself what to pick.",
  EMPTY_OR_SEARCH: "An empty list saying it is empty, or a search box's placeholder.",
  MAIL: "Written into an email, not shown on a screen.",
  NO_CALLER: "Reached only by an endpoint, or a request field, the web never sends.",
  NOT_DRAWN: "Carried with a reply's data, but nothing on screen draws it.",
} as const;

/** The guide describes the message: this phrase, which restates it, is in the guide. */
interface Described {
  described: RegExp;
}

/**
 * The guide leaves the message out, for this reason. A name only a screen
 * reader hears also carries the phrase that describes its control by look.
 */
interface Excluded {
  excluded: (typeof REASONS)[keyof typeof REASONS];
  look?: RegExp;
}

/** Every message the guide does not quote, and what the guide does with it. */
export const NOT_QUOTED: Readonly<Record<string, Described | Excluded>> = {
  "activity.description": { described: /the project's uploads, generations and changes to spaces and members/ },
  "activity.empty": { described: /the project's uploads, generations and changes to spaces and members/ },
  "activity.label": { excluded: REASONS.SCREEN_READER, look: /a pulse line/ },
  "activity.loading": { excluded: REASONS.PASSING },
  "activity.relative.daysAgo": { excluded: REASONS.FILLS_A_VALUE },
  "activity.relative.hoursAgo": { excluded: REASONS.FILLS_A_VALUE },
  "activity.relative.isoDate": { excluded: REASONS.FILLS_A_VALUE },
  "activity.relative.justNow": { excluded: REASONS.FILLS_A_VALUE },
  "activity.relative.minutesAgo": { excluded: REASONS.FILLS_A_VALUE },
  "activity.relative.monthsAgo": { excluded: REASONS.FILLS_A_VALUE },
  "activity.relative.weeksAgo": { excluded: REASONS.FILLS_A_VALUE },
  "activity.relative.yesterday": { excluded: REASONS.FILLS_A_VALUE },
  "activity.type.assetDeleted": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "activity.type.assetUploaded": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "activity.type.assetUploadedAudio": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "activity.type.assetUploadedImage": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "activity.type.assetUploadedVideo": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "activity.type.generationFailed": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "activity.type.generationSucceeded": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "activity.type.generationSucceededAudio": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "activity.type.generationSucceededImage": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "activity.type.generationSucceededTool": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "activity.type.generationSucceededVideo": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "activity.type.memberJoined": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "activity.type.memberRemoved": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "activity.type.memberRoleChanged": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "activity.type.ownershipTransferred": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "activity.type.spaceCreated": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "activity.type.spaceDeleted": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "activity.type.spaceLocked": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "activity.type.spaceRenamed": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "activity.type.spaceRestored": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "activity.type.spaceUnlocked": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "canvas.annotation.cannotWrite": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "canvas.annotation.noteGone": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "canvas.annotation.targetGone": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "canvas.annotation.unknownAuthor": { excluded: REASONS.FILLS_A_VALUE },
  "canvas.connection.kind3d": { excluded: REASONS.FILLS_A_VALUE },
  "canvas.connection.kindAnnotation": { excluded: REASONS.FILLS_A_VALUE },
  "canvas.connection.kindAudio": { excluded: REASONS.FILLS_A_VALUE },
  "canvas.connection.kindGroup": { excluded: REASONS.FILLS_A_VALUE },
  "canvas.connection.kindImage": { excluded: REASONS.FILLS_A_VALUE },
  "canvas.connection.kindText": { excluded: REASONS.FILLS_A_VALUE },
  "canvas.connection.kindVideo": { excluded: REASONS.FILLS_A_VALUE },
  "canvas.connection.kindWeb": { excluded: REASONS.FILLS_A_VALUE },
  "canvas.connection.rejected": { described: /snaps back with a message naming the two kinds/ },
  "canvas.contextMenu.clipboardError": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "canvas.emptyImage.color.black": { excluded: REASONS.SCREEN_READER, look: /with a set of swatches and a custom colour/ },
  "canvas.emptyImage.color.blue": { excluded: REASONS.SCREEN_READER, look: /with a set of swatches and a custom colour/ },
  "canvas.emptyImage.color.custom": { excluded: REASONS.SCREEN_READER, look: /a custom colour/ },
  "canvas.emptyImage.color.gray": { excluded: REASONS.SCREEN_READER, look: /with a set of swatches and a custom colour/ },
  "canvas.emptyImage.color.green": { excluded: REASONS.SCREEN_READER, look: /with a set of swatches and a custom colour/ },
  "canvas.emptyImage.color.lightGray": { excluded: REASONS.SCREEN_READER, look: /with a set of swatches and a custom colour/ },
  "canvas.emptyImage.color.orange": { excluded: REASONS.SCREEN_READER, look: /with a set of swatches and a custom colour/ },
  "canvas.emptyImage.color.red": { excluded: REASONS.SCREEN_READER, look: /with a set of swatches and a custom colour/ },
  "canvas.emptyImage.color.violet": { excluded: REASONS.SCREEN_READER, look: /with a set of swatches and a custom colour/ },
  "canvas.emptyImage.color.white": { excluded: REASONS.SCREEN_READER, look: /with a set of swatches and a custom colour/ },
  "canvas.emptyImage.color.yellow": { excluded: REASONS.SCREEN_READER, look: /with a set of swatches and a custom colour/ },
  "canvas.emptyImage.execute": { excluded: REASONS.SCREEN_READER, look: /the round button with an upward arrow replaces the picture/ },
  "canvas.emptyImage.exit": { excluded: REASONS.SCREEN_READER, look: /the X closes the panel without a change/ },
  "canvas.emptyImage.generateFailed": { excluded: REASONS.SAYS_TRY_AGAIN },
  "canvas.generatePanel.audioDialogueSummary": { excluded: REASONS.FILLS_A_VALUE },
  "canvas.generatePanel.audioLanguageSearch": { excluded: REASONS.EMPTY_OR_SEARCH },
  "canvas.generatePanel.audioOptionEmpty": { excluded: REASONS.EMPTY_OR_SEARCH },
  "canvas.generatePanel.audioParams": { excluded: REASONS.NOT_USED },
  "canvas.generatePanel.audioPromptPlaceholder": { excluded: REASONS.SAYS_WHAT_TO_TYPE },
  "canvas.generatePanel.audioReadingDialogue": { described: /or a dialogue for a number of speakers/ },
  "canvas.generatePanel.cameraBody": { described: /as well as the camera itself/ },
  "canvas.generatePanel.catalogNoModels": { excluded: REASONS.DEPLOYMENT },
  "canvas.generatePanel.characterImageTip": { excluded: REASONS.SAYS_WHAT_TO_PICK },
  "canvas.generatePanel.coverSongTip": { excluded: REASONS.SAYS_WHAT_TO_PICK },
  "canvas.generatePanel.creditsPerThousandChars": { excluded: REASONS.FILLS_A_VALUE },
  "canvas.generatePanel.drivingAudioTip": { excluded: REASONS.SAYS_WHAT_TO_PICK },
  "canvas.generatePanel.drivingVideoTip": { excluded: REASONS.SAYS_WHAT_TO_PICK },
  "canvas.generatePanel.durationSeconds": { excluded: REASONS.FILLS_A_VALUE },
  "canvas.generatePanel.endFrameTip": { excluded: REASONS.SAYS_WHAT_TO_PICK },
  "canvas.generatePanel.errorNoCharacterImage": { described: /A required slot left empty stops the run with a message naming it/ },
  "canvas.generatePanel.errorNoDrivingAudio": { described: /A required slot left empty stops the run with a message naming it/ },
  "canvas.generatePanel.errorNoDrivingVideo": { described: /A required slot left empty stops the run with a message naming it/ },
  "canvas.generatePanel.errorNoEndFrame": { described: /A required slot left empty stops the run with a message naming it/ },
  "canvas.generatePanel.errorNoLeftAudio": { described: /A required slot left empty stops the run with a message naming it/ },
  "canvas.generatePanel.errorNoMusicSong": { described: /A required slot left empty stops the run with a message naming it/ },
  "canvas.generatePanel.errorNoRefAudio": { described: /A required slot left empty stops the run with a message naming it/ },
  "canvas.generatePanel.errorNoReferenceMention": { described: /A video model that needs one says what is still missing/ },
  "canvas.generatePanel.errorNoRightAudio": { described: /A required slot left empty stops the run with a message naming it/ },
  "canvas.generatePanel.errorNoSourceVideo": { described: /A required slot left empty stops the run with a message naming it/ },
  "canvas.generatePanel.errorTooManyReferences": { described: /takes at most so many mentions of a kind; past that, pressing generate says the limit/ },
  "canvas.generatePanel.execute": { excluded: REASONS.SCREEN_READER, look: /press the round button with an upward arrow at the right end/ },
  "canvas.generatePanel.exit": { excluded: REASONS.SCREEN_READER, look: /an X at the far right that closes the panel/ },
  "canvas.generatePanel.firstFrameTip": { excluded: REASONS.SAYS_WHAT_TO_PICK },
  "canvas.generatePanel.focusCropDiscarded": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "canvas.generatePanel.focusCropTag": { excluded: REASONS.SCREEN_READER, look: /a crop icon before the source node's name/ },
  "canvas.generatePanel.focusSourceBusy": { described: /is replaced, starts processing, fails or is deleted while you crop it, the bar under it closes and a message says what happened/ },
  "canvas.generatePanel.focusSourceBusyByPeer": { described: /is replaced, starts processing, fails or is deleted while you crop it, the bar under it closes and a message says what happened/ },
  "canvas.generatePanel.focusSourceDeletedByPeer": { described: /is replaced, starts processing, fails or is deleted while you crop it, the bar under it closes and a message says what happened/ },
  "canvas.generatePanel.focusSourceFailed": { described: /is replaced, starts processing, fails or is deleted while you crop it, the bar under it closes and a message says what happened/ },
  "canvas.generatePanel.focusSourceReplaced": { described: /is replaced, starts processing, fails or is deleted while you crop it, the bar under it closes and a message says what happened/ },
  "canvas.generatePanel.focusSourceReplacedByPeer": { described: /is replaced, starts processing, fails or is deleted while you crop it, the bar under it closes and a message says what happened/ },
  "canvas.generatePanel.focusSourceUnavailable": { described: /is replaced, starts processing, fails or is deleted while you crop it, the bar under it closes and a message says what happened/ },
  "canvas.generatePanel.focusTimelineLabel": { excluded: REASONS.SCREEN_READER, look: /drag its timeline in that bar/ },
  "canvas.generatePanel.focusTip": { excluded: REASONS.SAYS_WHAT_TO_PICK },
  "canvas.generatePanel.focusUploadFailed": { excluded: REASONS.SAYS_TRY_AGAIN },
  "canvas.generatePanel.insertFocusCropNamed": { excluded: REASONS.SCREEN_READER, look: /Clicking a chip in the strip above the prompt inserts/ },
  "canvas.generatePanel.insertReferenceNamed": { excluded: REASONS.SCREEN_READER, look: /Clicking a chip in the strip above the prompt inserts/ },
  "canvas.generatePanel.itemsRemove": { excluded: REASONS.SCREEN_READER, look: /an X on each to remove it/ },
  "canvas.generatePanel.leftAudioTip": { excluded: REASONS.SAYS_WHAT_TO_PICK },
  "canvas.generatePanel.locateSource": { excluded: REASONS.SCREEN_READER, look: /a target-like icon beside the words/ },
  "canvas.generatePanel.mentionNoMatch": { excluded: REASONS.EMPTY_OR_SEARCH },
  "canvas.generatePanel.moodImageTip": { excluded: REASONS.SAYS_WHAT_TO_PICK },
  "canvas.generatePanel.musicLyricsPlaceholder": { excluded: REASONS.SAYS_WHAT_TO_TYPE },
  "canvas.generatePanel.musicMelodyTip": { excluded: REASONS.SAYS_WHAT_TO_PICK },
  "canvas.generatePanel.musicPromptPlaceholder": { excluded: REASONS.SAYS_WHAT_TO_TYPE },
  "canvas.generatePanel.musicSongTip": { excluded: REASONS.SAYS_WHAT_TO_PICK },
  "canvas.generatePanel.musicVocalTip": { excluded: REASONS.SAYS_WHAT_TO_PICK },
  "canvas.generatePanel.param.chaos": { excluded: REASONS.MODEL_SETTING_NAME },
  "canvas.generatePanel.param.distance": { excluded: REASONS.MODEL_SETTING_NAME },
  "canvas.generatePanel.param.creativity": { excluded: REASONS.MODEL_SETTING_NAME },
  "canvas.generatePanel.param.emotion": { excluded: REASONS.MODEL_SETTING_NAME },
  "canvas.generatePanel.param.enable_image_search": { excluded: REASONS.MODEL_SETTING_NAME },
  "canvas.generatePanel.param.enable_web_search": { excluded: REASONS.MODEL_SETTING_NAME },
  "canvas.generatePanel.param.horizontal_angle": { excluded: REASONS.MODEL_SETTING_NAME },
  "canvas.generatePanel.param.language": { excluded: REASONS.MODEL_SETTING_NAME },
  "canvas.generatePanel.param.loop": { excluded: REASONS.MODEL_SETTING_NAME },
  "canvas.generatePanel.param.model_mode": { excluded: REASONS.MODEL_SETTING_NAME },
  "canvas.generatePanel.param.motion": { excluded: REASONS.MODEL_SETTING_NAME },
  "canvas.generatePanel.param.negative_prompt": { excluded: REASONS.MODEL_SETTING_NAME },
  "canvas.generatePanel.param.order": { excluded: REASONS.MODEL_SETTING_NAME },
  "canvas.generatePanel.param.pronunciation_dict": { excluded: REASONS.MODEL_SETTING_NAME },
  "canvas.generatePanel.param.quality": { excluded: REASONS.MODEL_SETTING_NAME },
  "canvas.generatePanel.param.rendering": { excluded: REASONS.MODEL_SETTING_NAME },
  "canvas.generatePanel.param.speakers": { excluded: REASONS.MODEL_SETTING_NAME },
  "canvas.generatePanel.param.style_match": { excluded: REASONS.MODEL_SETTING_NAME },
  "canvas.generatePanel.param.stylize": { excluded: REASONS.MODEL_SETTING_NAME },
  "canvas.generatePanel.param.transparency": { excluded: REASONS.MODEL_SETTING_NAME },
  "canvas.generatePanel.param.vertical_angle": { excluded: REASONS.MODEL_SETTING_NAME },
  "canvas.generatePanel.param.weird": { excluded: REASONS.MODEL_SETTING_NAME },
  "canvas.generatePanel.paramField.pronunciation": { excluded: REASONS.MODEL_SETTING_NAME },
  "canvas.generatePanel.paramField.speaker": { excluded: REASONS.MODEL_SETTING_NAME },
  "canvas.generatePanel.paramField.text": { excluded: REASONS.MODEL_SETTING_NAME },
  "canvas.generatePanel.paramField.voice": { excluded: REASONS.MODEL_SETTING_NAME },
  "canvas.generatePanel.promptPlaceholder": { excluded: REASONS.SAYS_WHAT_TO_TYPE },
  "canvas.generatePanel.refAudioTip": { excluded: REASONS.SAYS_WHAT_TO_PICK },
  "canvas.generatePanel.referenceAddFailed": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "canvas.generatePanel.referencePoolFull": { described: /past it a new one is refused with a message naming the limit/ },
  "canvas.generatePanel.referenceTip": { excluded: REASONS.SAYS_WHAT_TO_PICK },
  "canvas.generatePanel.referenceTipAudio": { excluded: REASONS.SAYS_WHAT_TO_PICK },
  "canvas.generatePanel.refuseExecuteTooLong": { described: /Each model also caps how long its text may be; past that, pressing it says the limit/ },
  "canvas.generatePanel.refuseInsertTypeUnused": { described: /a faded chip shows a message saying why instead/ },
  "canvas.generatePanel.removeCharacterImage": { excluded: REASONS.SCREEN_READER, look: /The X on a filled slot empties it/ },
  "canvas.generatePanel.removeDrivingAudio": { excluded: REASONS.SCREEN_READER, look: /The X on a filled slot empties it/ },
  "canvas.generatePanel.removeDrivingVideo": { excluded: REASONS.SCREEN_READER, look: /The X on a filled slot empties it/ },
  "canvas.generatePanel.removeEndFrame": { excluded: REASONS.SCREEN_READER, look: /The X on a filled slot empties it/ },
  "canvas.generatePanel.removeFirstFrame": { excluded: REASONS.SCREEN_READER, look: /The X on a filled slot empties it/ },
  "canvas.generatePanel.removeFocusCropNamed": { excluded: REASONS.SCREEN_READER, look: /a focus crop's chip it deletes the crop/ },
  "canvas.generatePanel.removeLeftAudio": { excluded: REASONS.SCREEN_READER, look: /The X on a filled slot empties it/ },
  "canvas.generatePanel.removeMoodImage": { excluded: REASONS.SCREEN_READER, look: /The X on a filled slot empties it/ },
  "canvas.generatePanel.removeMusicMelody": { excluded: REASONS.SCREEN_READER, look: /The X on a filled slot empties it/ },
  "canvas.generatePanel.removeMusicSong": { excluded: REASONS.SCREEN_READER, look: /The X on a filled slot empties it/ },
  "canvas.generatePanel.removeMusicVocal": { excluded: REASONS.SCREEN_READER, look: /The X on a filled slot empties it/ },
  "canvas.generatePanel.removeRefAudio": { excluded: REASONS.SCREEN_READER, look: /The X on a filled slot empties it/ },
  "canvas.generatePanel.removeReferenceNamed": { excluded: REASONS.SCREEN_READER, look: /On a connected node's chip the X deletes/ },
  "canvas.generatePanel.removeRightAudio": { excluded: REASONS.SCREEN_READER, look: /The X on a filled slot empties it/ },
  "canvas.generatePanel.removeSourceVideo": { excluded: REASONS.SCREEN_READER, look: /The X on a filled slot empties it/ },
  "canvas.generatePanel.rightAudioTip": { excluded: REASONS.SAYS_WHAT_TO_PICK },
  "canvas.generatePanel.selectCharacterImageFromCanvas": { excluded: REASONS.SAYS_WHAT_TO_PICK },
  "canvas.generatePanel.selectCoverSongFromCanvas": { excluded: REASONS.SAYS_WHAT_TO_PICK },
  "canvas.generatePanel.selectDrivingAudioFromCanvas": { excluded: REASONS.SAYS_WHAT_TO_PICK },
  "canvas.generatePanel.selectDrivingVideoFromCanvas": { excluded: REASONS.SAYS_WHAT_TO_PICK },
  "canvas.generatePanel.selectEndFrameFromCanvas": { excluded: REASONS.SAYS_WHAT_TO_PICK },
  "canvas.generatePanel.selectFocusFromCanvas": { excluded: REASONS.SAYS_WHAT_TO_PICK },
  "canvas.generatePanel.selectFromCanvas": { excluded: REASONS.SAYS_WHAT_TO_PICK },
  "canvas.generatePanel.selectLeftAudioFromCanvas": { excluded: REASONS.SAYS_WHAT_TO_PICK },
  "canvas.generatePanel.selectMoodImageFromCanvas": { excluded: REASONS.SAYS_WHAT_TO_PICK },
  "canvas.generatePanel.selectMusicMelodyFromCanvas": { excluded: REASONS.SAYS_WHAT_TO_PICK },
  "canvas.generatePanel.selectMusicSongFromCanvas": { excluded: REASONS.SAYS_WHAT_TO_PICK },
  "canvas.generatePanel.selectMusicVocalFromCanvas": { excluded: REASONS.SAYS_WHAT_TO_PICK },
  "canvas.generatePanel.selectRefAudioFromCanvas": { excluded: REASONS.SAYS_WHAT_TO_PICK },
  "canvas.generatePanel.selectRightAudioFromCanvas": { excluded: REASONS.SAYS_WHAT_TO_PICK },
  "canvas.generatePanel.selectSoundVideoFromCanvas": { excluded: REASONS.SAYS_WHAT_TO_PICK },
  "canvas.generatePanel.selectSourceVideoFromCanvas": { excluded: REASONS.SAYS_WHAT_TO_PICK },
  "canvas.generatePanel.sfxDurationSeconds": { excluded: REASONS.FILLS_A_VALUE },
  "canvas.generatePanel.sfxPromptPlaceholder": { excluded: REASONS.SAYS_WHAT_TO_TYPE },
  "canvas.generatePanel.sourceVideoTip": { excluded: REASONS.SAYS_WHAT_TO_PICK },
  "canvas.generatePanel.videoPromptPlaceholder": { excluded: REASONS.SAYS_WHAT_TO_TYPE },
  "canvas.generatePanel.voiceEmpty": { excluded: REASONS.EMPTY_OR_SEARCH },
  "canvas.generatePanel.voiceLoading": { excluded: REASONS.PASSING },
  "canvas.generatePanel.voiceModelChanged": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "canvas.generatePanel.voiceMoreError": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "canvas.generatePanel.voiceSample": { excluded: REASONS.SCREEN_READER, look: /a play button on each voice that has a sample/ },
  "canvas.group.background": { excluded: REASONS.SCREEN_READER, look: /a colour swatch/ },
  "canvas.group.backgroundBlue": { described: /a no-colour dot and seven colours/ },
  "canvas.group.backgroundGreen": { described: /a no-colour dot and seven colours/ },
  "canvas.group.backgroundNone": { described: /a no-colour dot and seven colours/ },
  "canvas.group.backgroundOrange": { described: /a no-colour dot and seven colours/ },
  "canvas.group.backgroundPink": { described: /a no-colour dot and seven colours/ },
  "canvas.group.backgroundRed": { described: /a no-colour dot and seven colours/ },
  "canvas.group.backgroundTeal": { described: /a no-colour dot and seven colours/ },
  "canvas.group.backgroundViolet": { described: /a no-colour dot and seven colours/ },
  "canvas.history.close": { excluded: REASONS.SCREEN_READER, look: /closes with its X/ },
  "canvas.history.count": { excluded: REASONS.FILLS_A_VALUE },
  "canvas.history.snapshotEmpty": { described: /greyed while the node is empty/ },
  "canvas.history.snapshotFailed": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "canvas.minimap.label": { excluded: REASONS.SCREEN_READER, look: /The minimap can be dragged/ },
  "canvas.nodePlaceholder.3d": { excluded: REASONS.NOT_CREATABLE },
  "canvas.nodePlaceholder.audio": { described: /An empty picture, video or sound node shows its type icon/ },
  "canvas.nodePlaceholder.video": { described: /An empty picture, video or sound node shows its type icon/ },
  "canvas.nodePlaceholder.web": { excluded: REASONS.NOT_CREATABLE },
  "canvas.task.couldNotStart": { excluded: REASONS.SAYS_TRY_AGAIN },
  "canvas.task.countTip": { excluded: REASONS.FILLS_A_VALUE },
  "canvas.task.dismissFailed": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "canvas.task.elapsed": { excluded: REASONS.FILLS_A_VALUE },
  "canvas.task.endedAt": { excluded: REASONS.FILLS_A_VALUE },
  "canvas.task.failure.aborted": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "canvas.task.failure.declined": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "canvas.task.failure.empty": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "canvas.task.failure.expired": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "canvas.task.failure.internal": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "canvas.task.failure.media_refused": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "canvas.task.failure.no_credits": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "canvas.task.failure.no_result": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "canvas.task.failure.over_cap": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "canvas.task.failure.source_too_slow": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "canvas.task.failure.source_unreachable": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "canvas.task.failure.understand_over_cap": { described: /larger than a reading takes, or of a type it cannot read/ },
  "canvas.task.failure.understand_unsupported_type": { described: /larger than a reading takes, or of a type it cannot read/ },
  "canvas.task.failure.unsupported_type": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "canvas.task.panelClose": { excluded: REASONS.SCREEN_READER, look: /the list closes with its X/ },
  "canvas.task.panelEmpty": { excluded: REASONS.EMPTY_OR_SEARCH },
  "canvas.task.panelError": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "canvas.task.panelLoading": { excluded: REASONS.PASSING },
  "canvas.task.panelReload": { excluded: REASONS.SAYS_TRY_AGAIN },
  "canvas.task.remaining": { excluded: REASONS.FILLS_A_VALUE },
  "canvas.task.startedAt": { excluded: REASONS.FILLS_A_VALUE },
  "canvas.task.stillRunning": { excluded: REASONS.NOT_DRAWN },
  "canvas.upload.empty": { described: /An empty file makes no node, and a message names it/ },
  "canvas.upload.failed": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "canvas.upload.hashUnavailable": { excluded: REASONS.SAYS_TRY_AGAIN },
  "canvas.upload.tooLarge": { described: /over the size limit, makes no node, and a message names it/ },
  "canvas.upload.unsupportedType": { described: /in a format that is not supported, or over the size limit, makes no node, and a message names it/ },
  "chat.action.copied": { excluded: REASONS.PASSING },
  "chat.action.copy": { excluded: REASONS.SCREEN_READER, look: /Under a finished reply are a copy icon/ },
  "chat.assets.more": { excluded: REASONS.FILLS_A_VALUE },
  "chat.attachment.kind": { excluded: REASONS.FILLS_A_VALUE },
  "chat.attachment.more": { excluded: REASONS.FILLS_A_VALUE },
  "chat.attachment.nodes": { excluded: REASONS.FILLS_A_VALUE },
  "chat.backToLatest": { excluded: REASONS.SCREEN_READER, look: /a round button with a downward arrow at the bottom goes back to the latest/ },
  "chat.code.copy": { excluded: REASONS.SCREEN_READER, look: /A code block shows a copy icon when hovered/ },
  "chat.composer.atLimit": { described: /at the limit a line at the top of the box, above the text, says so/ },
  "chat.composer.attach": { excluded: REASONS.SCREEN_READER, look: /The plus sign at the bottom left of the box attaches/ },
  "chat.composer.attachFull": { described: /is said on a line beside the plus sign/ },
  "chat.composer.attachTooLarge": { described: /is said on a line beside the plus sign/ },
  "chat.composer.attachUnavailable": { described: /is said on a line beside the plus sign/ },
  "chat.composer.attachUnsupported": { described: /is said on a line beside the plus sign/ },
  "chat.composer.attachmentFailed": { described: /could not be uploaded or read shows a red mark and says why/ },
  "chat.composer.attachmentUploading": { excluded: REASONS.SCREEN_READER, look: /a spinner while it uploads/ },
  "chat.composer.chipsAria": { excluded: REASONS.SCREEN_READER, look: /Each attachment shows as a small chip/ },
  "chat.composer.inputAria": { excluded: REASONS.SCREEN_READER, look: /The empty box reads/ },
  "chat.composer.removeAttachment": { excluded: REASONS.SCREEN_READER, look: /its X removes it/ },
  "chat.composer.sending": { excluded: REASONS.PASSING },
  "chat.conversation.rowActions": { excluded: REASONS.SCREEN_READER, look: /hovering one shows three dots/ },
  "chat.empty.greetingDefault": { excluded: REASONS.FILLS_A_VALUE },
  "chat.empty.greetingWithName": { excluded: REASONS.FILLS_A_VALUE },
  "chat.empty.quick.findReference": { excluded: REASONS.SAYS_WHAT_TO_TYPE },
  "chat.empty.quick.refinePrompt": { excluded: REASONS.SAYS_WHAT_TO_TYPE },
  "chat.empty.quick.writePrompt": { excluded: REASONS.SAYS_WHAT_TO_TYPE },
  "chat.history.description": { excluded: REASONS.SCREEN_READER, look: /the earlier conversations, most recently used first/ },
  "chat.history.loading": { excluded: REASONS.PASSING },
  "chat.history.loadingMore": { excluded: REASONS.PASSING },
  "chat.load.failedBody": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "chat.markdown.backToReference": { excluded: REASONS.FILLS_A_VALUE },
  "chat.markdown.footnotes": { excluded: REASONS.FILLS_A_VALUE },
  "chat.markdown.taskDone": { excluded: REASONS.SCREEN_READER, look: /shows each item's box ticked or empty/ },
  "chat.markdown.taskTodo": { excluded: REASONS.SCREEN_READER, look: /shows each item's box ticked or empty/ },
  "chat.message.waiting": { excluded: REASONS.SCREEN_READER, look: /a small dot pulses at its end/ },
  "chat.relative.daysAgo": { excluded: REASONS.FILLS_A_VALUE },
  "chat.relative.hoursAgo": { excluded: REASONS.FILLS_A_VALUE },
  "chat.relative.isoDate": { excluded: REASONS.FILLS_A_VALUE },
  "chat.relative.justNow": { excluded: REASONS.FILLS_A_VALUE },
  "chat.relative.minutesAgo": { excluded: REASONS.FILLS_A_VALUE },
  "chat.relative.monthsAgo": { excluded: REASONS.FILLS_A_VALUE },
  "chat.relative.weeksAgo": { excluded: REASONS.FILLS_A_VALUE },
  "chat.relative.yesterday": { excluded: REASONS.FILLS_A_VALUE },
  "chat.tool.checkingCanvas": { described: /a line may name what it is doing/ },
  "chat.tool.checkingModels": { described: /a line may name what it is doing/ },
  "chat.tool.failure.unreachable": { described: /A step that failed while the reply carried on leaves a red line/ },
  "chat.tool.failure.upstream": { described: /A step that failed while the reply carried on leaves a red line/ },
  "chat.tool.failureTimes": { described: /share one line, followed by a multiplication sign and how many times/ },
  "chat.tool.judging": { described: /a line may name what it is doing/ },
  "chat.tool.proposingNodes": { described: /a line may name what it is doing/ },
  "chat.tool.running": { described: /a line may name what it is doing/ },
  "chat.tool.searching": { described: /a line may name what it is doing/ },
  "chat.tool.searchingImages": { described: /a line may name what it is doing/ },
  "chat.tool.understanding": { described: /a line may name what it is doing/ },
  "chat.tool.unfinished": { excluded: REASONS.NOT_DRAWN },
  "chrome.aria.agentColumnWidth": { excluded: REASONS.SCREEN_READER, look: /dragging the line between it and the space/ },
  "chrome.aria.backToStudio": { excluded: REASONS.SCREEN_READER, look: /an arrow with the word Studio/ },
  "chrome.aria.creditsBalance": { excluded: REASONS.SCREEN_READER, look: /a star with the credits left/ },
  "chrome.aria.home": { excluded: REASONS.SCREEN_READER, look: /the brand mark/ },
  "chrome.aria.language": { excluded: REASONS.SCREEN_READER, look: /a globe with the current language/ },
  "chrome.aria.openSpaces": { excluded: REASONS.SCREEN_READER, look: /tabs along the top/ },
  "chrome.aria.scrollTabsLeft": { excluded: REASONS.SCREEN_READER, look: /arrows at either end scroll them/ },
  "chrome.aria.scrollTabsRight": { excluded: REASONS.SCREEN_READER, look: /arrows at either end scroll them/ },
  "chrome.aria.spacesToolbar": { excluded: REASONS.SCREEN_READER, look: /tabs along the top/ },
  "chrome.aria.theme": { excluded: REASONS.SCREEN_READER, look: /an icon for the theme/ },
  "chrome.languageNotSaved": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "chrome.tooltip.agentHide": { excluded: REASONS.SCREEN_READER, look: /a panel icon, hides or shows it/ },
  "chrome.tooltip.agentShow": { excluded: REASONS.SCREEN_READER, look: /a panel icon, hides or shows it/ },
  "chrome.tooltip.newConversation": { excluded: REASONS.SCREEN_READER, look: /a plus sign, which starts a new conversation/ },
  "chrome.tooltip.newSpace": { excluded: REASONS.SCREEN_READER, look: /The first, a plus sign, opens/ },
  "chrome.tooltip.notifications": { excluded: REASONS.SCREEN_READER, look: /Last is a bell/ },
  "chrome.tooltip.openHistory": { excluded: REASONS.SCREEN_READER, look: /two speech bubbles, which open/ },
  "chrome.tooltip.revealActiveTab": { excluded: REASONS.SCREEN_READER, look: /a crosshair button scrolls the current tab into view/ },
  "chrome.tooltip.share": { excluded: REASONS.SCREEN_READER, look: /a person icon with a plus/ },
  "common.clipboardError": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "common.loading": { excluded: REASONS.PASSING },
  "common.pageUnavailable.action": { excluded: REASONS.SAYS_TRY_AGAIN },
  "common.pageUnavailable.message": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "members.modal.description": { described: /There each member's row has a list to change their role/ },
  "members.modal.isMe": { excluded: REASONS.FILLS_A_VALUE },
  "members.modal.membersSection": { excluded: REASONS.FILLS_A_VALUE },
  "members.modal.removeConfirmBody": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "members.modal.removeFailed": { excluded: REASONS.SAYS_TRY_AGAIN },
  "members.modal.removeSuccess": { excluded: REASONS.ECHO },
  "members.modal.roleChangeFailed": { excluded: REASONS.SAYS_TRY_AGAIN },
  "members.modal.roleChanged": { excluded: REASONS.ECHO },
  "members.modal.roleSelectAria": { excluded: REASONS.SCREEN_READER, look: /a list to change their role/ },
  "members.modal.transferFailed": { excluded: REASONS.SAYS_TRY_AGAIN },
  "members.modal.transferHint": { described: /Nothing changes until that member accepts/ },
  "members.modal.transferPending": { described: /says it is waiting for them/ },
  "members.modal.transferPendingUnnamed": { described: /says it is waiting for them/ },
  "members.modal.transferSuccess": { excluded: REASONS.ECHO },
  "members.modal.transferWithdrawFailed": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "members.modal.transferWithdrawn": { excluded: REASONS.ECHO },
  "members.popover.isMe": { excluded: REASONS.FILLS_A_VALUE },
  "members.stack.triggerAria": { excluded: REASONS.SCREEN_READER, look: /the members' pictures with a small arrow/ },
  "membership.period.month": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "membership.period.year": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "menu.createAria": { excluded: REASONS.SCREEN_READER, look: /a floating menu of icons runs along the left edge/ },
  "menu.disabledTooltip": { excluded: REASONS.VIEWERS_ONLY },
  "notFound.body": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "notFound.cta": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "notFound.heading": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "notifications.actorFallback": { excluded: REASONS.FILLS_A_VALUE },
  "notifications.empty": { excluded: REASONS.EMPTY_OR_SEARCH },
  "notifications.expiresLabel.hours": { excluded: REASONS.FILLS_A_VALUE },
  "notifications.expiresLabel.minutes": { excluded: REASONS.FILLS_A_VALUE },
  "notifications.headline.membershipEnded": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "notifications.headline.membershipUpgradeIncomplete": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "notifications.headline.membershipUpgradeIncompleteNoPeriod": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "notifications.headline.projectInviteAccepted": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "notifications.headline.projectInviteRequest": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "notifications.headline.projectJoinApproved": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "notifications.headline.projectJoinRejected": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "notifications.headline.projectJoinRequest": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "notifications.headline.projectTransferApproved": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "notifications.headline.projectTransferRequest": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "notifications.headline.roleUpgradeApproved": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "notifications.headline.roleUpgradeRejected": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "notifications.headline.roleUpgradeRequest": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "notifications.headline.studioInviteAccepted": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "notifications.headline.studioInviteRequest": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "notifications.headline.studioTransferApproved": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "notifications.headline.studioTransferRequest": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "notifications.loading": { excluded: REASONS.PASSING },
  "notifications.subtitle.invitedAsEditor": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "notifications.subtitle.invitedAsGuest": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "notifications.subtitle.invitedAsMaintainer": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "notifications.subtitle.invitedAsViewer": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "notifications.subtitle.projectTransferHint": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "notifications.subtitle.studioTransferHint": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "project.header.renameFailed": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "project.space.error.create": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "project.space.error.notSynced": { excluded: REASONS.SAYS_TRY_AGAIN },
  "project.space.error.unreachable": { excluded: REASONS.SAYS_TRY_AGAIN },
  "project.space.timeout.create": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "project.space.timeout.retry": { excluded: REASONS.SAYS_TRY_AGAIN },
  "projectJoin.body": { excluded: REASONS.OUTSIDERS_ONLY },
  "projectJoin.cancel": { excluded: REASONS.OUTSIDERS_ONLY },
  "projectJoin.loadFailed": { excluded: REASONS.OUTSIDERS_ONLY },
  "projectJoin.messageLabel": { excluded: REASONS.OUTSIDERS_ONLY },
  "projectJoin.messagePlaceholder": { excluded: REASONS.OUTSIDERS_ONLY },
  "projectJoin.ok": { excluded: REASONS.OUTSIDERS_ONLY },
  "projectJoin.pendingBody": { excluded: REASONS.OUTSIDERS_ONLY },
  "projectJoin.pendingTitle": { excluded: REASONS.OUTSIDERS_ONLY },
  "projectJoin.request": { excluded: REASONS.OUTSIDERS_ONLY },
  "projectJoin.requestFailed": { excluded: REASONS.OUTSIDERS_ONLY },
  "projectJoin.sentBody": { excluded: REASONS.OUTSIDERS_ONLY },
  "projectJoin.sentTitle": { excluded: REASONS.OUTSIDERS_ONLY },
  "projectJoin.title": { excluded: REASONS.OUTSIDERS_ONLY },
  "projectJoin.withdraw": { excluded: REASONS.OUTSIDERS_ONLY },
  "projectJoin.withdrawFailed": { excluded: REASONS.OUTSIDERS_ONLY },
  "roleTag.upgradeRequest.ariaLabel": { excluded: REASONS.VIEWERS_ONLY },
  "roleTag.upgradeRequest.description": { excluded: REASONS.VIEWERS_ONLY },
  "roleTag.upgradeRequest.pendingAriaLabel": { excluded: REASONS.VIEWERS_ONLY },
  "roleTag.upgradeRequest.pendingDescription": { excluded: REASONS.VIEWERS_ONLY },
  "roleTag.upgradeRequest.pendingTitle": { excluded: REASONS.VIEWERS_ONLY },
  "roleTag.upgradeRequest.placeholder": { excluded: REASONS.VIEWERS_ONLY },
  "roleTag.upgradeRequest.sending": { excluded: REASONS.VIEWERS_ONLY },
  "roleTag.upgradeRequest.submit": { excluded: REASONS.VIEWERS_ONLY },
  "roleTag.upgradeRequest.title": { excluded: REASONS.VIEWERS_ONLY },
  "roleTag.upgradeRequest.toast.failed": { excluded: REASONS.VIEWERS_ONLY },
  "roleTag.upgradeRequest.toast.sent": { excluded: REASONS.VIEWERS_ONLY },
  "roleTag.upgradeRequest.toast.withdrawFailed": { excluded: REASONS.VIEWERS_ONLY },
  "roleTag.upgradeRequest.toast.withdrawn": { excluded: REASONS.VIEWERS_ONLY },
  "roleTag.upgradeRequest.withdraw": { excluded: REASONS.VIEWERS_ONLY },
  "roleTag.upgradeRequest.withdrawing": { excluded: REASONS.VIEWERS_ONLY },
  "server.auth.email_taken": { excluded: REASONS.NOT_ON_THESE_SCREENS },
  "server.auth.google_email_unverified": { excluded: REASONS.NOT_ON_THESE_SCREENS },
  "server.auth.google_link_requires_email_login": { excluded: REASONS.NOT_ON_THESE_SCREENS },
  "server.auth.google_oauth_unconfigured": { excluded: REASONS.NOT_ON_THESE_SCREENS },
  "server.auth.invalid_credentials": { excluded: REASONS.NOT_ON_THESE_SCREENS },
  "server.auth.invalid_google_credential": { excluded: REASONS.NOT_ON_THESE_SCREENS },
  "server.auth.invalid_recovery_code": { excluded: REASONS.NOT_ON_THESE_SCREENS },
  "server.auth.invalid_reset_token": { excluded: REASONS.NOT_ON_THESE_SCREENS },
  "server.auth.logout_success": { excluded: REASONS.NOT_ON_THESE_SCREENS },
  "server.auth.not_authenticated": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "server.auth.reset_link_sent": { excluded: REASONS.NOT_ON_THESE_SCREENS },
  "server.auth.reset_recovery_success": { excluded: REASONS.NOT_ON_THESE_SCREENS },
  "server.auth.reset_success": { excluded: REASONS.NOT_ON_THESE_SCREENS },
  "server.auth.signup_code_exhausted": { excluded: REASONS.NOT_ON_THESE_SCREENS },
  "server.auth.signup_code_invalid": { excluded: REASONS.NOT_ON_THESE_SCREENS },
  "server.auth.signup_code_send_failed": { excluded: REASONS.NOT_ON_THESE_SCREENS },
  "server.auth.signup_expired": { excluded: REASONS.NOT_ON_THESE_SCREENS },
  "server.auth.signup_resend_cooldown": { excluded: REASONS.NOT_ON_THESE_SCREENS },
  "server.auth.token_expired": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "server.canvas.history_entry_not_found": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "server.canvas.model_requires_source": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "server.canvas.too_many_inputs": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "server.canvas.voices_model_not_found": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "server.canvas.voices_not_offered": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "server.chat.attachments_too_long": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "server.chat.attachments_too_many": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "server.chat.message_too_long": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "server.conversation.attachment_limit_reached": { excluded: REASONS.NO_CALLER },
  "server.conversation.attachment_not_found": { excluded: REASONS.NO_CALLER },
  "server.conversation.attachment_not_yours": { excluded: REASONS.NO_CALLER },
  "server.conversation.not_found": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "server.credit.designation_locked": { excluded: REASONS.NOT_ON_THESE_SCREENS },
  "server.credit.designation_not_purchased": { excluded: REASONS.NOT_ON_THESE_SCREENS },
  "server.credit.granted_elsewhere": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "server.credit.in_debt": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "server.credit.not_studio_admin": { excluded: REASONS.NOT_ON_THESE_SCREENS },
  "server.credit.refund_already_asked": { excluded: REASONS.NOT_ON_THESE_SCREENS },
  "server.credit.refund_already_spent": { excluded: REASONS.NOT_ON_THESE_SCREENS },
  "server.credit.refund_not_purchased": { excluded: REASONS.NOT_ON_THESE_SCREENS },
  "server.credit.refund_still_designated": { excluded: REASONS.NOT_ON_THESE_SCREENS },
  "server.credit.refund_window_closed": { excluded: REASONS.NOT_ON_THESE_SCREENS },
  "server.credit.unassigned": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "server.error.conflict": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "server.error.forbidden": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "server.error.insufficient_credits": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "server.error.internal": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "server.error.not_found": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "server.error.rate_limited": { excluded: REASONS.SAYS_TRY_AGAIN },
  "server.error.upload_empty": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "server.error.upload_too_large": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "server.error.validation": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "server.mail.expiry.invitation": { excluded: REASONS.MAIL },
  "server.mail.expiry.request": { excluded: REASONS.MAIL },
  "server.mail.expiry.transfer": { excluded: REASONS.MAIL },
  "server.mail.footer": { excluded: REASONS.MAIL },
  "server.mail.help": { excluded: REASONS.MAIL },
  "server.mail.legal.about": { excluded: REASONS.MAIL },
  "server.mail.legal.privacy": { excluded: REASONS.MAIL },
  "server.mail.legal.terms": { excluded: REASONS.MAIL },
  "server.mail.membership_ended.footer": { excluded: REASONS.MAIL },
  "server.mail.membership_ended.lead": { excluded: REASONS.MAIL },
  "server.mail.membership_ended.subject": { excluded: REASONS.MAIL },
  "server.mail.password_reset.action": { excluded: REASONS.MAIL },
  "server.mail.password_reset.footer": { excluded: REASONS.MAIL },
  "server.mail.password_reset.lead": { excluded: REASONS.MAIL },
  "server.mail.password_reset.subject": { excluded: REASONS.MAIL },
  "server.mail.project_invite.action": { excluded: REASONS.MAIL },
  "server.mail.project_invite.lead": { excluded: REASONS.MAIL },
  "server.mail.project_invite.subject": { excluded: REASONS.MAIL },
  "server.mail.project_join.action": { excluded: REASONS.MAIL },
  "server.mail.project_join.lead": { excluded: REASONS.MAIL },
  "server.mail.project_join.subject": { excluded: REASONS.MAIL },
  "server.mail.project_transfer.action": { excluded: REASONS.MAIL },
  "server.mail.project_transfer.lead": { excluded: REASONS.MAIL },
  "server.mail.project_transfer.subject": { excluded: REASONS.MAIL },
  "server.mail.reason": { excluded: REASONS.MAIL },
  "server.mail.role_upgrade.action": { excluded: REASONS.MAIL },
  "server.mail.role_upgrade.lead": { excluded: REASONS.MAIL },
  "server.mail.role_upgrade.subject": { excluded: REASONS.MAIL },
  "server.mail.signup_code.footer": { excluded: REASONS.MAIL },
  "server.mail.signup_code.lead": { excluded: REASONS.MAIL },
  "server.mail.signup_code.subject": { excluded: REASONS.MAIL },
  "server.mail.storage_full.footer": { excluded: REASONS.MAIL },
  "server.mail.storage_full.lead": { excluded: REASONS.MAIL },
  "server.mail.storage_full.subject": { excluded: REASONS.MAIL },
  "server.mail.studio_invite.action": { excluded: REASONS.MAIL },
  "server.mail.studio_invite.lead": { excluded: REASONS.MAIL },
  "server.mail.studio_invite.subject": { excluded: REASONS.MAIL },
  "server.mail.studio_transfer.action": { excluded: REASONS.MAIL },
  "server.mail.studio_transfer.lead": { excluded: REASONS.MAIL },
  "server.mail.studio_transfer.subject": { excluded: REASONS.MAIL },
  "server.membership.already_subscribed": { excluded: REASONS.NOT_ON_THESE_SCREENS },
  "server.membership.change_not_offered": { excluded: REASONS.NOT_ON_THESE_SCREENS },
  "server.membership.change_unconfirmed": { excluded: REASONS.NOT_ON_THESE_SCREENS },
  "server.membership.checkout_not_found": { excluded: REASONS.NOT_ON_THESE_SCREENS },
  "server.membership.checkout_unconfirmed": { excluded: REASONS.NOT_ON_THESE_SCREENS },
  "server.membership.no_subscription": { excluded: REASONS.NOT_ON_THESE_SCREENS },
  "server.membership.not_cancelling": { excluded: REASONS.NOT_ON_THESE_SCREENS },
  "server.membership.payment_overdue": { excluded: REASONS.NOT_ON_THESE_SCREENS },
  "server.membership.same_tier": { excluded: REASONS.NOT_ON_THESE_SCREENS },
  "server.membership.unavailable": { excluded: REASONS.DEPLOYMENT },
  "server.payment.consent-credits-v1": { excluded: REASONS.NOT_ON_THESE_SCREENS },
  "server.payment.consent-credits-v2": { excluded: REASONS.NOT_ON_THESE_SCREENS },
  "server.payment.not_found": { excluded: REASONS.NOT_ON_THESE_SCREENS },
  "server.payment.price_not_configured": { excluded: REASONS.NOT_ON_THESE_SCREENS },
  "server.payment.refund-credits-v1.expired": { excluded: REASONS.NOT_ON_THESE_SCREENS },
  "server.payment.refund-credits-v1.unused": { excluded: REASONS.NOT_ON_THESE_SCREENS },
  "server.payment.refund-credits-v1.used": { excluded: REASONS.NOT_ON_THESE_SCREENS },
  "server.payment.refund-credits-v2.expired": { excluded: REASONS.NOT_ON_THESE_SCREENS },
  "server.payment.refund-credits-v2.unassigned": { excluded: REASONS.NOT_ON_THESE_SCREENS },
  "server.payment.refund-credits-v2.unused": { excluded: REASONS.NOT_ON_THESE_SCREENS },
  "server.payment.refund-credits-v2.used": { excluded: REASONS.NOT_ON_THESE_SCREENS },
  "server.payment.refund-credits-v3.expired": { excluded: REASONS.NOT_ON_THESE_SCREENS },
  "server.payment.refund-credits-v3.purchased": { excluded: REASONS.NOT_ON_THESE_SCREENS },
  "server.payment.refund-credits-v3.unassigned": { excluded: REASONS.NOT_ON_THESE_SCREENS },
  "server.payment.refund-credits-v3.unused": { excluded: REASONS.NOT_ON_THESE_SCREENS },
  "server.payment.refund-credits-v3.used": { excluded: REASONS.NOT_ON_THESE_SCREENS },
  "server.payment.tier_not_found": { excluded: REASONS.NOT_ON_THESE_SCREENS },
  "server.payment.unavailable": { excluded: REASONS.DEPLOYMENT },
  "server.project.collaborator_limit_reached": { described: /a full project says how many collaborators its plan allows: the plan of the studio.s admin, so only their upgrade raises it/ },
  "server.project.collaborator_limit_reached_for_invitee": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "server.project.join_already_member": { excluded: REASONS.OUTSIDERS_ONLY },
  "server.project.join_already_pending": { excluded: REASONS.OUTSIDERS_ONLY },
  "server.project.limit_reached": { excluded: REASONS.NOT_ON_THESE_SCREENS },
  "server.project.no_active_owner": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "server.project.not_found": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "server.project.only_viewer_can_request_upgrade": { excluded: REASONS.VIEWERS_ONLY },
  "server.purchase_mail.consent_heading": { excluded: REASONS.MAIL },
  "server.purchase_mail.credits_amount": { excluded: REASONS.MAIL },
  "server.purchase_mail.fact_line": { excluded: REASONS.MAIL },
  "server.purchase_mail.intro": { excluded: REASONS.MAIL },
  "server.purchase_mail.label.balance": { excluded: REASONS.MAIL },
  "server.purchase_mail.label.credits": { excluded: REASONS.MAIL },
  "server.purchase_mail.label.order_ref": { excluded: REASONS.MAIL },
  "server.purchase_mail.label.purchased_at": { excluded: REASONS.MAIL },
  "server.purchase_mail.label.refund_by": { excluded: REASONS.MAIL },
  "server.purchase_mail.label.subtotal": { excluded: REASONS.MAIL },
  "server.purchase_mail.label.tax": { excluded: REASONS.MAIL },
  "server.purchase_mail.label.total": { excluded: REASONS.MAIL },
  "server.purchase_mail.refund_heading": { excluded: REASONS.MAIL },
  "server.purchase_mail.subject": { excluded: REASONS.MAIL },
  "server.purchase_mail.support": { excluded: REASONS.MAIL },
  "server.skill.already_installed": { excluded: REASONS.NO_CALLER },
  "server.skill.cannot_install_own": { excluded: REASONS.NO_CALLER },
  "server.skill.name_taken": { excluded: REASONS.NO_CALLER },
  "server.skill.not_available_here": { excluded: REASONS.NO_CALLER },
  "server.skill.not_available_on_deployment": { excluded: REASONS.NO_CALLER },
  "server.skill.not_found": { excluded: REASONS.NO_CALLER },
  "server.skill.not_found_named": { excluded: REASONS.NO_CALLER },
  "server.skill.not_published": { excluded: REASONS.NO_CALLER },
  "server.skill.not_user_invocable": { excluded: REASONS.NO_CALLER },
  "server.storage.download_not_downloadable": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "server.storage.quota_exceeded_generate": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "server.storage.quota_exceeded_upload": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "server.studio.already_invited": { excluded: REASONS.NOT_ON_THESE_SCREENS },
  "server.studio.already_member": { excluded: REASONS.NOT_ON_THESE_SCREENS },
  "server.studio.cannot_change_admin_role": { excluded: REASONS.NOT_ON_THESE_SCREENS },
  "server.studio.cannot_modify_personal": { described: /a personal studio takes no other members/ },
  "server.studio.email_not_registered": { excluded: REASONS.NOT_ON_THESE_SCREENS },
  "server.studio.leave_last_admin": { excluded: REASONS.NOT_ON_THESE_SCREENS },
  "server.studio.member_limit_reached": { excluded: REASONS.NOT_ON_THESE_SCREENS },
  "server.studio.member_limit_reached_for_invitee": { excluded: REASONS.NOT_ON_THESE_SCREENS },
  "server.studio.remove_last_admin": { excluded: REASONS.NOT_ON_THESE_SCREENS },
  "server.studio.slug_taken": { excluded: REASONS.NOT_ON_THESE_SCREENS },
  "server.studio.team_limit_reached": { excluded: REASONS.NOT_ON_THESE_SCREENS },
  "server.text_tool.already_running": { excluded: REASONS.NO_CALLER },
  "share.copyInviteLink": { excluded: REASONS.SCREEN_READER, look: /with a copy icon beside it/ },
  "share.inviteFailed": { excluded: REASONS.SAYS_TRY_AGAIN },
  "share.inviteLinkCopied": { excluded: REASONS.ECHO },
  "share.inviteLinkCopyFailed": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "share.inviteSending": { excluded: REASONS.PASSING },
  "share.inviteSent": { excluded: REASONS.ECHO },
  "spaces.create.description": { described: /type a name under/ },
  "spaces.create.namePlaceholder": { excluded: REASONS.SAYS_WHAT_TO_TYPE },
  "spaces.create.nameRemaining": { excluded: REASONS.FILLS_A_VALUE },
  "spaces.create.typeAria": { excluded: REASONS.SCREEN_READER, look: /card \(/ },
  "spaces.create.typeLabel": { excluded: REASONS.FILLS_A_VALUE },
  "spaces.document.blockHandle.dragTip": { excluded: REASONS.SCREEN_READER, look: /a handle of six dots/ },
  "spaces.document.blockHandle.insertHere": { excluded: REASONS.SCREEN_READER, look: /shows a plus at its left/ },
  "spaces.document.commands.aiOtherGroup": { excluded: REASONS.NOT_OPEN },
  "spaces.document.commands.aiProduceGroup": { excluded: REASONS.NOT_OPEN },
  "spaces.document.commands.aiRewriteGroup": { excluded: REASONS.NOT_OPEN },
  "spaces.document.commands.ai_custom": { excluded: REASONS.NOT_OPEN },
  "spaces.document.commands.ai_expand": { excluded: REASONS.NOT_OPEN },
  "spaces.document.commands.ai_illustrate": { excluded: REASONS.NOT_OPEN },
  "spaces.document.commands.ai_refine": { excluded: REASONS.NOT_OPEN },
  "spaces.document.commands.ai_shorten": { excluded: REASONS.NOT_OPEN },
  "spaces.document.commands.ai_storyboard": { excluded: REASONS.NOT_OPEN },
  "spaces.document.commands.ai_tone": { excluded: REASONS.NOT_OPEN },
  "spaces.document.commands.ai_translate": { excluded: REASONS.NOT_OPEN },
  "spaces.document.commands.bold": { excluded: REASONS.SCREEN_READER, look: /bold B, italic I, strikethrough S and underline U icons, a link icon, a code/ },
  "spaces.document.commands.code": { excluded: REASONS.SCREEN_READER, look: /bold B, italic I, strikethrough S and underline U icons, a link icon, a code/ },
  "spaces.document.commands.comingLabel": { excluded: REASONS.SCREEN_READER, look: /a sparkle with the word/ },
  "spaces.document.commands.italic": { excluded: REASONS.SCREEN_READER, look: /bold B, italic I, strikethrough S and underline U icons, a link icon, a code/ },
  "spaces.document.commands.link": { excluded: REASONS.SCREEN_READER, look: /a link icon/ },
  "spaces.document.commands.strike": { excluded: REASONS.SCREEN_READER, look: /bold B, italic I, strikethrough S and underline U icons, a link icon, a code/ },
  "spaces.document.commands.underline": { excluded: REASONS.SCREEN_READER, look: /bold B, italic I, strikethrough S and underline U icons, a link icon, a code/ },
  "spaces.document.comment.closeRail": { excluded: REASONS.SCREEN_READER, look: /and an X that closes it/ },
  "spaces.document.comment.deleteReply": { excluded: REASONS.SCREEN_READER, look: /each later reply has a small X/ },
  "spaces.document.docMenu.label": { excluded: REASONS.SCREEN_READER, look: /Three dots at the top right open/ },
  "spaces.document.schemaOutdated.published": { excluded: REASONS.FILLS_A_VALUE },
  "spaces.document.schemaOutdated.risksLead": { described: /warns above the button that/ },
  "spaces.drawer.action.deleteConfirmDescription": { described: /says the owner can restore it/ },
  "spaces.drawer.action.deleteConfirmTitle": { described: /which asks whether to delete the space by name/ },
  "spaces.drawer.action.deleteFail": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "spaces.drawer.action.lockFail": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "spaces.drawer.action.operationFail": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "spaces.drawer.action.unlockFail": { excluded: REASONS.SAYS_WHAT_HAPPENED },
  "spaces.drawer.description": { excluded: REASONS.FILLS_A_VALUE },
  "spaces.drawer.empty": { excluded: REASONS.EMPTY_OR_SEARCH },
  "spaces.drawer.label": { excluded: REASONS.SCREEN_READER, look: /three lines with the number of spaces/ },
  "spaces.drawer.openAria": { excluded: REASONS.SCREEN_READER, look: /Clicking a row opens that space as a tab/ },
  "spaces.kind.canvasSub": { excluded: REASONS.FILLS_A_VALUE },
  "spaces.kind.documentSub": { excluded: REASONS.FILLS_A_VALUE },
  "spaces.kind.timeline": { described: /a third, greyed card is marked/ },
  "spaces.kind.timelineSub": { excluded: REASONS.FILLS_A_VALUE },
  "spaces.lockedAria": { excluded: REASONS.SCREEN_READER, look: /small padlock after its name/ },
  "spaces.readonly.canvas.description": { excluded: REASONS.READ_ONLY_PANEL },
  "spaces.readonly.canvas.title": { excluded: REASONS.READ_ONLY_PANEL },
  "spaces.readonly.description": { excluded: REASONS.READ_ONLY_PANEL },
  "spaces.readonly.document.description": { excluded: REASONS.READ_ONLY_PANEL },
  "spaces.readonly.document.title": { excluded: REASONS.READ_ONLY_PANEL },
  "spaces.readonly.label": { excluded: REASONS.READ_ONLY_PANEL },
  "spaces.readonly.timeline.description": { excluded: REASONS.READ_ONLY_PANEL },
  "spaces.readonly.timeline.title": { excluded: REASONS.READ_ONLY_PANEL },
  "spaces.rename.error.failed": { excluded: REASONS.SAYS_TRY_AGAIN },
  "spaces.rename.inputAriaLabel": { excluded: REASONS.SCREEN_READER, look: /Double-click the name/ },
  "spaces.tab.closeAria": { excluded: REASONS.SCREEN_READER, look: /a small X at its right end, which closes the tab/ },
  "viewportToolbar.aria": { excluded: REASONS.SCREEN_READER, look: /At the bottom right of a canvas is a bar/ },
  "viewportToolbar.fitAria": { excluded: REASONS.SCREEN_READER, look: /four corner/ },
  "viewportToolbar.minimap.hide": { excluded: REASONS.SCREEN_READER, look: /each a solid square while on/ },
  "viewportToolbar.minimap.show": { excluded: REASONS.SCREEN_READER, look: /each a solid square while on/ },
  "viewportToolbar.snap.off": { excluded: REASONS.SCREEN_READER, look: /each a solid square while on/ },
  "viewportToolbar.snap.on": { excluded: REASONS.SCREEN_READER, look: /each a solid square while on/ },
  "viewportToolbar.zoomCustomAria": { excluded: REASONS.SCREEN_READER, look: /a box to type any value from 10/ },
  "viewportToolbar.zoomResetAria": { excluded: REASONS.SCREEN_READER, look: /Clicking the/ },
};
