/**
 * Application error hierarchy.
 *
 * Service layer throws AppError subclasses; the global error-handler
 * middleware converts them to structured JSON responses.
 */

/** Base application error with an HTTP status code. */
export class AppError extends Error {
  /** HTTP status code to return. */
  public readonly statusCode: number;

  /**
   * @param statusCode - HTTP status code
   * @param message - Human-readable error message
   */
  constructor(statusCode: number, message: string) {
    super(message);
    this.name = "AppError";
    this.statusCode = statusCode;
  }
}

/** Resource not found (404). */
export class NotFoundError extends AppError {
  /**
   * Construct a 404 error.
   * @param message - human-readable description of the missing resource
   */
  constructor(message: string) {
    super(404, message);
    this.name = "NotFoundError";
  }
}

/** Resource conflict (409). */
export class ConflictError extends AppError {
  /**
   * Construct a 409 error.
   * @param message - human-readable description of the conflicting state
   */
  constructor(message: string) {
    super(409, message);
    this.name = "ConflictError";
  }
}

/** Validation failed (422). */
export class ValidationError extends AppError {
  /**
   * Construct a 422 error.
   * @param message - human-readable description of the validation failure
   */
  constructor(message: string) {
    super(422, message);
    this.name = "ValidationError";
  }
}

/** Access forbidden (403). */
export class ForbiddenError extends AppError {
  /**
   * Construct a 403 error.
   * @param message - human-readable description of why access is denied
   */
  constructor(message: string) {
    super(403, message);
    this.name = "ForbiddenError";
  }
}

/** Not authenticated (401). */
export class UnauthorizedError extends AppError {
  /**
   * Construct a 401 error.
   * @param message - human-readable description of the authentication failure
   */
  constructor(message: string) {
    super(401, message);
    this.name = "UnauthorizedError";
  }
}

/**
 * Detail payload returned alongside `ConflictLockedError` 409 responses.
 * Carries the lock-holder identity + start time so the client can render
 * a "node X is being generated by Y (12s elapsed)" toast (spec §10.15.3).
 */
export interface ConflictLockedDetail {
  /** UserId of the lock holder, or null if the holder task / user lookup failed. */
  holdingBy: string | null;
  /** Display name of the holder, defaults to a generic "someone" when unknown. */
  holdingByName: string;
  /** TaskId currently holding the lock, or null when the lookup failed. */
  taskId: string | null;
  /** Epoch ms when the holder started the task. */
  startedAt: number;
  /** Estimated total seconds for the holder's task (for progress UI). */
  estimatedSeconds: number;
}

/**
 * Returned by `POST /canvas/tasks` when `mode='overwrite'` and the target
 * canvas node is already locked by another in-flight task. The client uses
 * the `detail` payload to render the conflict toast (spec §10.15.3 / §10.15.6).
 *
 * Distinct from the generic `ConflictError` (409) so the error handler can
 * preserve the structured `detail` field on the wire instead of flattening
 * to `{message}`.
 */
export class ConflictLockedError extends AppError {
  public readonly detail: ConflictLockedDetail;
  /**
   * Construct a 409 lock-conflict error carrying the lock-holder detail.
   * @param detail - lock-holder identity and timing used to render the conflict toast
   */
  constructor(detail: ConflictLockedDetail) {
    super(409, "Node is locked by another in-flight task");
    this.name = "ConflictLockedError";
    this.detail = detail;
  }
}
