/**
 * Canvas node types shared between frontend, Collab, and server.
 *
 * Implements the history-based model introduced in the 2026-04-26
 * Yjs + Editor redesign (spec §3 Data Model, §4.6 Mini-tool execution).
 *
 * Each node carries an ordered `history` timeline of `HistoryItem`
 * entries and an `activeHistoryId` pointer that identifies which entry
 * is currently published to the canvas.  There is no longer a
 * "state machine" (idle/handling) — lifecycle is expressed through
 * each `HistoryItem`'s own `status` field ("loading" | "done" | "failed").
 *
 * See `breatic-inner/design/2026-04-26-yjs-editor-redesign/spec.md`
 * sections 3 and 4.6 for the full specification.
 */

/** Lifecycle stage of a single history entry. */
export type HistoryItemStatus = "loading" | "done" | "failed";

/** Origin of a history entry — who or what created it. */
export type HistoryItemSource =
  | "apply"
  | "canvas-ai"
  | "editor-mini-tool"
  | "upload";

/**
 * A single versioned result stored in a node's history timeline.
 *
 * At runtime, each entry is serialised as a `Y.Map` inside the node's
 * `data.history` `Y.Array`.  Writers (frontend or worker) generate
 * the `id` (UUID v4) before pushing.
 */
export interface HistoryItem {
  /** UUID v4 generated by the writer (frontend or worker). */
  id: string;
  /** OSS URL of the result; valid when status === "done". */
  url: string;
  /** Thumbnail URL (video / 3D); equals url for image. */
  cover?: string;
  /** Pixel dimensions (image / video). */
  width?: number;
  /** Pixel dimensions (image / video). */
  height?: number;
  /** Duration in seconds (video / audio). */
  duration?: number;
  /** Creator (for collaboration display). */
  by: { userId: string; name: string };
  /** Creation time, epoch milliseconds. */
  createdAt: number;
  /** Origin of this entry. */
  source: HistoryItemSource;
  /** Tool name when source != "apply" (e.g., "image.remove-bg"). */
  tool?: string;
  /** Tool input params (e.g., { brightness: 12 }). */
  params?: Record<string, unknown>;
  /** AIGC prompt when applicable. */
  prompt?: string;
  /** Lifecycle stage. */
  status: HistoryItemStatus;
  /** Human-readable error when status === "failed". */
  errorMessage?: string;
}

/**
 * Attachment reference stored in a node's `attachments` Y.Array.
 *
 * Each attachment is a `Y.Map` at runtime with these keys. The
 * `id` is used inside TipTap `@` Mention nodes for reference.
 */
export interface AttachRef {
  id: string;
  url: string;
  name: string;
  mimeType: string;
  size: number;
  uploadedAt: string;
}

/**
 * Documents the keys on each node's Y.Map in the canvas document.
 *
 * Structure mirrors ReactFlow's `{ id, type, position, data }`:
 *
 * ```
 * nodeMap: Y.Map
 *   ├── id:              string
 *   ├── type:            string
 *   ├── position:        Y.Map { x, y }
 *   └── data:            Y.Map              ← nested, matches ReactFlow
 *         ├── name:             string
 *         ├── activeHistoryId:  string | undefined
 *         ├── history:          Y.Array<Y.Map>
 *         ├── attachments:      Y.Array<Y.Map>
 *         ├── prompt:           Y.XmlFragment
 *         └── childIds:         string[] | undefined   (group nodes only)
 * ```
 *
 * This is a documentation type — you never instantiate it.
 */
export interface CanvasNodeFields {
  /** Stable node ID (immutable after creation). */
  id: string;
  /** Modality: "1001" text, "1002" image, "1003" video, "1004" audio, "group". */
  type: string;
  /** Canvas coordinates — Y.Map { x, y } at runtime. */
  position: { x: number; y: number };
  /** Nested data — Y.Map at runtime, matches ReactFlow node.data. */
  data: {
    /** Display label. */
    name: string;
    /** UUID of the history item currently published to canvas. */
    activeHistoryId?: string;
    /** Shared timeline of versions. Y.Array<Y.Map> at runtime. */
    history: HistoryItem[];
    /** Per-node upload pool. Y.Array<Y.Map> at runtime. */
    attachments: AttachRef[];
    /** Rich text prompt. Y.XmlFragment at runtime. */
    prompt: unknown;
    /** Group: child node IDs. Group has NO activeHistoryId / history. */
    childIds?: string[];
  };
}

// ── Event bus payloads ──────────────────────────────────

/**
 * All canvas and node events share a single Yjs document per project:
 * `"project-{projectId}"`.  There are no longer separate per-node docs
 * (`project-{id}/node/{nodeId}` is gone).  The `nodeId` field on the
 * event identifies which node inside that document to update.
 *
 * See `packages/collab/src/schema.ts` for the canonical `projectDocName`
 * builder and its parser.
 */

/**
 * Emitted by the worker (or any writer) to update a single history
 * entry inside a node's Y.Array.  The collab consumer merges
 * `update` into the target `HistoryItem` identified by `historyItemId`.
 *
 * Replaces the former `NodeHandlingEvent` / `NodeCompletedEvent` /
 * `NodeFailedEvent` trio — one shape, one code path.
 */
export interface HistoryUpdateEvent {
  type: "history-update";
  /** Always "project-{projectId}" — no more per-node docs. */
  docName: string;
  /** Node whose history is being updated. */
  nodeId: string;
  /** UUID of the history item to update (matches HistoryItem.id). */
  historyItemId: string;
  /** Partial update merged into the target item by the collab consumer. */
  update: Partial<HistoryItem>;
}

/** Union of all node state events on the task-events bus. */
export type NodeEvent = HistoryUpdateEvent;
