// Copyright (c) 2026 Orime, Inc.
// SPDX-License-Identifier: LicenseRef-BSAL-1.0

/**
 * Pure planner for "wrap the current selection in a Group" (group
 * redesign 2026-06-23). A Group owns an authoritative size, so this computes
 * the Group's stored position + width/height (members' padded bounding box) and
 * each member's position relative to the Group top-left. Kept ReactFlow-agnostic
 * (a plan, not a mutation) so it is unit-tested in isolation; the canvas applies
 * the plan to Yjs and clears the members' selection in its own buffer.
 */

import type { Node } from '@xyflow/react';

import { canJoinGroup } from '@web/spaces/canvas/group-membership';
import {
  EMPTY_NODE_SIZE,
  groupRectForMembers,
  rectContainsPoint,
  toRelativePosition,
  type Rect,
} from '@web/spaces/canvas/group-geometry';

/** One member's new position (relative to the Group top-left) after wrapping. */
interface GroupMemberPlan {
  id: string;
  position: { x: number; y: number };
}

/** The Yjs + local-state changes that wrapping a selection in a Group implies. */
export interface GroupCreationPlan {
  /** Id for the new Group node (generated by the caller for purity). */
  groupId: string;
  /** The Group's stored top-left (members' padded bounding-box top-left). */
  position: { x: number; y: number };
  /** The Group's authoritative width. */
  width: number;
  /** The Group's authoritative height. */
  height: number;
  /** Members bound to the Group, each with its new parent-relative position. */
  members: GroupMemberPlan[];
}

/** A Group a batch could land in, with the rect it is drawn as. */
export interface OpenGroup {
  id: string;
  rect: Rect;
}

/** Where a batch of freshly created nodes belongs. */
export type BatchGrouping =
  | { kind: 'join'; groupId: string; members: GroupMemberPlan[] }
  | { kind: 'wrap'; plan: GroupCreationPlan }
  | { kind: 'loose' };

/**
 * Where one upload batch belongs: inside the Group it was dropped on, in a
 * Group of its own, or nowhere.
 *
 * Files handed over together arrive as one thing, so they land as one. Dropped
 * on open canvas that means a Group around them; dropped on a Group it means
 * joining it, because a Group cannot hold a Group — wrapping the batch there
 * would put it in a box that can never become part of what it was dropped into.
 * @param created - The nodes the batch just made, top-level and unmeasured.
 * @param openGroups - The Groups that may take members, with their drawn rects.
 * @param origin - Where the drop landed.
 * @param origin.x - The drop point's x coordinate.
 * @param origin.y - The drop point's y coordinate.
 * @param newGroupId - Pre-generated id, used only when a new Group is made.
 * @returns What the caller should write.
 */
export function planBatchGrouping(
  created: ReadonlyArray<Node>,
  openGroups: ReadonlyArray<OpenGroup>,
  origin: { x: number; y: number },
  newGroupId: string,
): BatchGrouping {
  const host = openGroups.find((group) =>
    rectContainsPoint(group.rect, origin),
  );
  if (host !== undefined) {
    return {
      kind: 'join',
      groupId: host.id,
      members: created.map((node) => ({
        id: node.id,
        position: toRelativePosition(node.position, host.rect),
      })),
    };
  }
  const plan = planGroupCreation(
    created,
    created.map((node) => node.id),
    newGroupId,
  );
  return plan === null ? { kind: 'loose' } : { kind: 'wrap', plan };
}

/**
 * The member's rendered footprint in canvas coordinates, falling back to a
 * default cell before ReactFlow has measured it.
 * @param node - The member flow node.
 * @returns Its absolute bounding rect.
 */
function flowNodeRect(node: Node): Rect {
  const width = node.measured?.width ?? node.width ?? EMPTY_NODE_SIZE.width;
  const height = node.measured?.height ?? node.height ?? EMPTY_NODE_SIZE.height;
  return {
    x: node.position.x,
    y: node.position.y,
    width: width || EMPTY_NODE_SIZE.width,
    height: height || EMPTY_NODE_SIZE.height,
  };
}

/**
 * Plan wrapping the selected nodes in a Group: the Group's stored position +
 * size and each member's parent-relative position. Returns `null` when fewer
 * than two nodes are selected (nothing to wrap).
 * @param flowNodes - The current render buffer.
 * @param selectedIds - Ids of the nodes to wrap (the current selection).
 * @param groupId - Pre-generated id for the new Group node.
 * @returns The Group-creation plan, or `null` when fewer than two nodes are selected.
 */
export function planGroupCreation(
  flowNodes: ReadonlyArray<Node>,
  selectedIds: ReadonlyArray<string>,
  groupId: string,
): GroupCreationPlan | null {
  if (selectedIds.length < 2) return null;
  const ids = new Set(selectedIds);
  const members = flowNodes.filter(
    (node) => ids.has(node.id) && canJoinGroup(node.type),
  );
  // Whatever the user picked, a Group needs two things it may actually hold.
  if (members.length < 2) return null;
  const rect = groupRectForMembers(members.map(flowNodeRect));
  if (!rect) return null;
  const position = { x: rect.x, y: rect.y };
  const memberPlans = members.map((member) => ({
    id: member.id,
    position: toRelativePosition(member.position, position),
  }));
  return {
    groupId,
    position,
    width: rect.width,
    height: rect.height,
    members: memberPlans,
  };
}
