// Copyright (c) 2026 Orime, Inc.
// SPDX-License-Identifier: LicenseRef-BSAL-1.0

/**
 * Pure planner for "wrap the current selection in a Group" (group
 * redesign 2026-06-23). A Group owns an authoritative size, so this computes
 * the Group's stored position + width/height (members' padded bounding box) and
 * each member's position relative to the Group top-left. It also deselects the
 * wrapped members in the render buffer — the #1477 carry-over: clear the marquee
 * selection immediately so the Yjs mirror round-trip can't leave a stale
 * multi-selection that routes a right-click to the selection menu. Kept
 * ReactFlow-agnostic (a plan, not a mutation) so it is unit-tested in isolation;
 * the canvas applies the plan to Yjs + its render buffer.
 */

import type { Node } from '@xyflow/react';

import {
  groupRectForMembers,
  toRelativePosition,
  type Rect,
} from '@web/spaces/canvas/group-geometry';

/** Footprint assumed for a member ReactFlow has not measured yet. */
const DEFAULT_NODE_WIDTH = 160;
const DEFAULT_NODE_HEIGHT = 96;

/** One member's new position (relative to the Group top-left) after wrapping. */
interface GroupMemberPlan {
  id: string;
  position: { x: number; y: number };
}

/** The Yjs + local-state changes that wrapping a selection in a Group implies. */
export interface GroupCreationPlan {
  /** Id for the new Group node (generated by the caller for purity). */
  groupId: string;
  /** The Group's stored top-left (members' padded bounding-box top-left). */
  position: { x: number; y: number };
  /** The Group's authoritative width. */
  width: number;
  /** The Group's authoritative height. */
  height: number;
  /** Members bound to the Group, each with its new parent-relative position. */
  members: GroupMemberPlan[];
}

/**
 * The member's rendered footprint in canvas coordinates, falling back to a
 * default cell before ReactFlow has measured it.
 * @param node - The member flow node.
 * @returns Its absolute bounding rect.
 */
function flowNodeRect(node: Node): Rect {
  const width = node.measured?.width ?? node.width ?? DEFAULT_NODE_WIDTH;
  const height = node.measured?.height ?? node.height ?? DEFAULT_NODE_HEIGHT;
  return {
    x: node.position.x,
    y: node.position.y,
    width: width || DEFAULT_NODE_WIDTH,
    height: height || DEFAULT_NODE_HEIGHT,
  };
}

/**
 * Plan wrapping the selected nodes in a Group: the Group's stored position +
 * size, each member's parent-relative position, and the render buffer with the
 * wrapped members deselected (the #1477 fix). Returns `null` when fewer than two
 * nodes are selected (nothing to wrap).
 * @param flowNodes - The current render buffer.
 * @param selectedIds - Ids of the nodes to wrap (the current selection).
 * @param groupId - Pre-generated id for the new Group node.
 * @returns The Group-creation plan, or `null` when fewer than two nodes are selected.
 */
export function planGroupCreation(
  flowNodes: ReadonlyArray<Node>,
  selectedIds: ReadonlyArray<string>,
  groupId: string,
): GroupCreationPlan | null {
  if (selectedIds.length < 2) return null;
  const ids = new Set(selectedIds);
  const members = flowNodes.filter((node) => ids.has(node.id));
  const rect = groupRectForMembers(members.map(flowNodeRect));
  if (!rect) return null;
  const position = { x: rect.x, y: rect.y };
  const memberPlans = members.map((member) => ({
    id: member.id,
    position: toRelativePosition(member.position, position),
  }));
  return {
    groupId,
    position,
    width: rect.width,
    height: rect.height,
    members: memberPlans,
  };
}

/**
 * The buffer with every node that just went into a Group deselected (#1477).
 *
 * Clearing the selection before the new Group mirrors back keeps the round trip
 * from holding a stale multi-selection, which ReactFlow would route a
 * right-click to the SELECTION menu on instead of the Group menu.
 *
 * This reads whatever the buffer holds at the moment it runs, so the nodes it
 * leaves alone keep the coordinates the canvas is drawing them at — a
 * collaborator's drag included.
 * @param nodes - The buffer as it stands.
 * @param memberIds - The nodes that went into the Group.
 * @returns The buffer with those deselected, others by reference.
 */
export function deselectGrouped(
  nodes: ReadonlyArray<Node>,
  memberIds: ReadonlyArray<string>,
): Node[] {
  const ids = new Set(memberIds);
  return nodes.map((node) =>
    ids.has(node.id) && node.selected ? { ...node, selected: false } : node,
  );
}
