// Copyright (c) 2026 Orime, Inc.
// SPDX-License-Identifier: LicenseRef-BSAL-1.0

/**
 * Filling the one address every deployment plays the voice samples from
 * (#2156, #2239). A sample already served there is left alone, so a run with
 * nothing new only asks, and a rerun makes only what a previous run could not.
 */

import type { ResumeContext } from "@worker/providers/shared.js";
import type { VoiceSampleJob } from "@worker/voice-samples/plan.js";

/** The key the storage check asks about. */
const PROBE_KEY = "voice-samples/probe.mp3";

/**
 * Stop before generating anything when this machine's storage settings would
 * put the samples somewhere no deployment reads them from.
 * @param storageUrl - Where the storage settings publish a key.
 * @param sampleUrl - Where every deployment plays a sample key from.
 * @throws {Error} When the two addresses differ.
 */
export function assertUploadsReachSampleAddress(
  storageUrl: (key: string) => string,
  sampleUrl: (key: string) => string,
): void {
  const stored = storageUrl(PROBE_KEY);
  const played = sampleUrl(PROBE_KEY);
  if (stored !== played) {
    throw new Error(
      `The storage settings publish ${PROBE_KEY} at ${stored}, but every deployment plays it from ${played}`,
    );
  }
}

/**
 * What a HEAD on a sample's public address says about it.
 *
 * Only a 404 means the sample is not there. Any other failure (a bucket that
 * is not public, a rate limit, an outage) leaves that unknown, and making the
 * sample again would be paid for without making it playable.
 * @param key - The sample key, for the error.
 * @param status - The HEAD's status.
 * @returns True when served, false when missing.
 * @throws {Error} When the status answers neither.
 */
export function servedFromHead(key: string, status: number): boolean {
  if (status >= 200 && status < 300) return true;
  if (status === 404) return false;
  throw new Error(`${key}: HEAD answered ${status}`);
}

/** What a sync needs from the outside. */
export interface SyncDeps {
  /** Whether the sample address already serves this key. */
  exists: (key: string) => Promise<boolean>;
  /** Run the paid prediction and answer where its output is. */
  predict: (job: VoiceSampleJob) => Promise<string>;
  /** Fetch the prediction's output. */
  download: (url: string) => Promise<Buffer>;
  /** What is done to the generated bytes before they are stored. */
  finish?: (job: VoiceSampleJob, bytes: Buffer) => Promise<Buffer>;
  /** Store the bytes under the key. */
  upload: (key: string, bytes: Buffer) => Promise<void>;
  /** Checks that what follows a prediction can run; awaited once, before the first prediction, when a sample is missing. */
  beforeMaking?: () => Promise<void>;
  /** How many passes a failing sample gets. */
  attempts: number;
  /** How many samples are made at once. */
  concurrency?: number;
}

/** What a sync did. */
export interface SyncReport {
  /** Samples the sample address already served. */
  present: number;
  /** Samples made and stored. */
  made: number;
  /** Samples still missing after every pass, with the last error. */
  failed: Array<{ key: string; error: string }>;
}

/**
 * Run each job through `work`, a few at a time.
 * @param jobs - The jobs.
 * @param concurrency - How many at once.
 * @param work - What to do with one.
 */
async function eachLimited<T>(jobs: readonly T[], concurrency: number, work: (job: T) => Promise<void>): Promise<void> {
  const queue = [...jobs];
  await Promise.all(
    Array.from({ length: Math.min(concurrency, queue.length) }, async () => {
      for (let job = queue.shift(); job !== undefined; job = queue.shift()) await work(job);
    }),
  );
}

/**
 * Make every sample the sample address does not serve yet.
 * @param jobs - Every sample the catalog names.
 * @param deps - Sample address, generator, storage and pass count.
 * @returns How many were there, made, and still missing.
 */
export async function syncVoiceSamples(jobs: readonly VoiceSampleJob[], deps: SyncDeps): Promise<SyncReport> {
  const concurrency = deps.concurrency ?? 8;
  const missing: VoiceSampleJob[] = [];
  await eachLimited(jobs, concurrency, async (job) => {
    if (!(await deps.exists(job.key))) missing.push(job);
  });
  // Kept in catalog order, whatever order the checks answered in.
  missing.sort((a, b) => jobs.indexOf(a) - jobs.indexOf(b));

  if (missing.length > 0) await deps.beforeMaking?.();

  let made = 0;
  let pending = missing;
  const errors = new Map<string, string>();
  for (let pass = 0; pass < deps.attempts && pending.length > 0; pass += 1) {
    const failedThisPass: VoiceSampleJob[] = [];
    await eachLimited(pending, concurrency, async (job) => {
      try {
        const raw = await deps.download(await deps.predict(job));
        await deps.upload(job.key, deps.finish ? await deps.finish(job, raw) : raw);
        made += 1;
        errors.delete(job.key);
      } catch (err) {
        errors.set(job.key, err instanceof Error ? err.message : String(err));
        failedThisPass.push(job);
      }
    });
    pending = failedThisPass.sort((a, b) => jobs.indexOf(a) - jobs.indexOf(b));
  }
  return {
    present: jobs.length - missing.length,
    made,
    failed: pending.map((job) => ({ key: job.key, error: errors.get(job.key) ?? "" })),
  };
}

/**
 * A prediction that is paid for once per sample across passes: the upstream
 * task it submitted is kept by sample key, and a later pass polls that task
 * again. A task the upstream itself failed is dropped, so the next pass
 * submits a new one.
 * @param run - Runs one prediction with the resume context it is given.
 * @param startsOver - Whether an error means the upstream failed the task.
 * @returns The prediction step for {@link syncVoiceSamples}.
 */
export function resumablePredict(
  run: (job: VoiceSampleJob, resume: ResumeContext) => Promise<string>,
  startsOver: (err: unknown) => boolean,
): (job: VoiceSampleJob) => Promise<string> {
  const submitted = new Map<string, string>();
  return async (job) => {
    try {
      return await run(job, {
        storedTaskId: submitted.get(job.key) ?? null,
        persistTaskId: async (id) => {
          submitted.set(job.key, id);
        },
        externalTaskId: job.key,
      });
    } catch (err) {
      if (startsOver(err)) submitted.delete(job.key);
      throw err;
    }
  };
}
